//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AATbl_Gral_SolicitudConfiguracionTipo
    {
        public decimal SolicitudTipo_id { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionEnOficio { get; set; }
        public string CobroAsociadoHtml_td { get; set; }
        public Nullable<decimal> AnioVigencia { get; set; }
        public string FormatoSolicitud_Codigo { get; set; }
        public Nullable<System.DateTime> FormatoSolicitud_Fecha { get; set; }
        public string FormatoSolicitud_Version { get; set; }
        public string BoletaDeDecision_Codigo { get; set; }
        public Nullable<System.DateTime> BoletaDeDecision_Fecha { get; set; }
        public string BoletaDeDecision_Version { get; set; }
        public string InformeTecnico_Codigo { get; set; }
        public Nullable<System.DateTime> InformeTecnico_Fecha { get; set; }
        public string InformeTecnico_Version { get; set; }
        public string TipoRegistro { get; set; }
    }
}
