//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_RNF_APIEntities : DbContext
    {
        public db_RNF_APIEntities()
            : base("name=db_RNF_APIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_API_Gral_Especie> Tbl_API_Gral_Especie { get; set; }
        public virtual DbSet<Tbl_API_Sol_Finca> Tbl_API_Sol_Finca { get; set; }
        public virtual DbSet<Tbl_API_Sol_Rodal> Tbl_API_Sol_Rodal { get; set; }
        public virtual DbSet<Tbl_API_Sol_Rodal_Dasometrico> Tbl_API_Sol_Rodal_Dasometrico { get; set; }
        public virtual DbSet<Tbl_API_Sol_Rodal_Dasometrico_CentroParcela_Local> Tbl_API_Sol_Rodal_Dasometrico_CentroParcela_Local { get; set; }
        public virtual DbSet<Tbl_API_Sol_Rodal_Dasometrico_Local> Tbl_API_Sol_Rodal_Dasometrico_Local { get; set; }
        public virtual DbSet<Tbl_API_Sol_Rodal_Dasometrico_Manual> Tbl_API_Sol_Rodal_Dasometrico_Manual { get; set; }
        public virtual DbSet<Tbl_API_Sol_Rodal_Dasometrico_ValidacionesDiametrica_Local> Tbl_API_Sol_Rodal_Dasometrico_ValidacionesDiametrica_Local { get; set; }
        public virtual DbSet<Tbl_API_Sol_Rodal_Descuento> Tbl_API_Sol_Rodal_Descuento { get; set; }
        public virtual DbSet<Tbl_API_Sol_Rodal_Descuento_Local> Tbl_API_Sol_Rodal_Descuento_Local { get; set; }
        public virtual DbSet<Tbl_API_Sol_Rodal_Descuento_Poligono> Tbl_API_Sol_Rodal_Descuento_Poligono { get; set; }
        public virtual DbSet<Tbl_API_Sol_Rodal_Descuento_Poligono_Local> Tbl_API_Sol_Rodal_Descuento_Poligono_Local { get; set; }
        public virtual DbSet<Tbl_API_Sol_Rodal_Local> Tbl_API_Sol_Rodal_Local { get; set; }
        public virtual DbSet<Tbl_API_Sol_Rodal_Poligono> Tbl_API_Sol_Rodal_Poligono { get; set; }
        public virtual DbSet<Tbl_API_Sol_Rodal_Poligono_Local> Tbl_API_Sol_Rodal_Poligono_Local { get; set; }
        public virtual DbSet<Tbl_API_Sol_Solicitud> Tbl_API_Sol_Solicitud { get; set; }
    
        [DbFunction("db_RNF_APIEntities", "fc_API_GetLongitudLatitud")]
        public virtual IQueryable<fc_API_GetLongitudLatitud_Result> fc_API_GetLongitudLatitud(Nullable<decimal> gTMX, Nullable<decimal> gTMy)
        {
            var gTMXParameter = gTMX.HasValue ?
                new ObjectParameter("GTMX", gTMX) :
                new ObjectParameter("GTMX", typeof(decimal));
    
            var gTMyParameter = gTMy.HasValue ?
                new ObjectParameter("GTMy", gTMy) :
                new ObjectParameter("GTMy", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_API_GetLongitudLatitud_Result>("[db_RNF_APIEntities].[fc_API_GetLongitudLatitud](@GTMX, @GTMy)", gTMXParameter, gTMyParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_API_GetRegistro")]
        public virtual IQueryable<fc_API_GetRegistro_Result> fc_API_GetRegistro(string guid)
        {
            var guidParameter = guid != null ?
                new ObjectParameter("Guid", guid) :
                new ObjectParameter("Guid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_API_GetRegistro_Result>("[db_RNF_APIEntities].[fc_API_GetRegistro](@Guid)", guidParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_API_GetResumenFinca_DictamenTecnico")]
        public virtual IQueryable<fc_API_GetResumenFinca_DictamenTecnico_Result> fc_API_GetResumenFinca_DictamenTecnico(Nullable<long> solicitud_id, Nullable<long> finca_id)
        {
            var solicitud_idParameter = solicitud_id.HasValue ?
                new ObjectParameter("Solicitud_id", solicitud_id) :
                new ObjectParameter("Solicitud_id", typeof(long));
    
            var finca_idParameter = finca_id.HasValue ?
                new ObjectParameter("Finca_id", finca_id) :
                new ObjectParameter("Finca_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_API_GetResumenFinca_DictamenTecnico_Result>("[db_RNF_APIEntities].[fc_API_GetResumenFinca_DictamenTecnico](@Solicitud_id, @Finca_id)", solicitud_idParameter, finca_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_API_GetSolicitud")]
        public virtual IQueryable<fc_API_GetSolicitud_Result> fc_API_GetSolicitud(string guid)
        {
            var guidParameter = guid != null ?
                new ObjectParameter("Guid", guid) :
                new ObjectParameter("Guid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_API_GetSolicitud_Result>("[db_RNF_APIEntities].[fc_API_GetSolicitud](@Guid)", guidParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_API_GetSolicitudDasometricoCentroParcela")]
        public virtual IQueryable<fc_API_GetSolicitudDasometricoCentroParcela_Result> fc_API_GetSolicitudDasometricoCentroParcela(Nullable<long> solicitud_id)
        {
            var solicitud_idParameter = solicitud_id.HasValue ?
                new ObjectParameter("Solicitud_id", solicitud_id) :
                new ObjectParameter("Solicitud_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_API_GetSolicitudDasometricoCentroParcela_Result>("[db_RNF_APIEntities].[fc_API_GetSolicitudDasometricoCentroParcela](@Solicitud_id)", solicitud_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_API_GetSolicitudFinca")]
        public virtual IQueryable<fc_API_GetSolicitudFinca_Result> fc_API_GetSolicitudFinca(Nullable<long> solicitud_id)
        {
            var solicitud_idParameter = solicitud_id.HasValue ?
                new ObjectParameter("Solicitud_id", solicitud_id) :
                new ObjectParameter("Solicitud_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_API_GetSolicitudFinca_Result>("[db_RNF_APIEntities].[fc_API_GetSolicitudFinca](@Solicitud_id)", solicitud_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_API_GetSolicitudRodal")]
        public virtual IQueryable<fc_API_GetSolicitudRodal_Result> fc_API_GetSolicitudRodal(Nullable<long> solicitud_id)
        {
            var solicitud_idParameter = solicitud_id.HasValue ?
                new ObjectParameter("Solicitud_id", solicitud_id) :
                new ObjectParameter("Solicitud_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_API_GetSolicitudRodal_Result>("[db_RNF_APIEntities].[fc_API_GetSolicitudRodal](@Solicitud_id)", solicitud_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_API_PlantacionVoluntaria")]
        public virtual IQueryable<fc_API_PlantacionVoluntaria_Result> fc_API_PlantacionVoluntaria(Nullable<long> solicitud_id)
        {
            var solicitud_idParameter = solicitud_id.HasValue ?
                new ObjectParameter("Solicitud_id", solicitud_id) :
                new ObjectParameter("Solicitud_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_API_PlantacionVoluntaria_Result>("[db_RNF_APIEntities].[fc_API_PlantacionVoluntaria](@Solicitud_id)", solicitud_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_API_RodalDescuento")]
        public virtual IQueryable<fc_API_RodalDescuento_Result> fc_API_RodalDescuento(Nullable<long> solicitud_id)
        {
            var solicitud_idParameter = solicitud_id.HasValue ?
                new ObjectParameter("Solicitud_id", solicitud_id) :
                new ObjectParameter("Solicitud_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_API_RodalDescuento_Result>("[db_RNF_APIEntities].[fc_API_RodalDescuento](@Solicitud_id)", solicitud_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_API_RodalDescuentoPoligono")]
        public virtual IQueryable<fc_API_RodalDescuentoPoligono_Result> fc_API_RodalDescuentoPoligono(Nullable<long> solicitud_id)
        {
            var solicitud_idParameter = solicitud_id.HasValue ?
                new ObjectParameter("Solicitud_id", solicitud_id) :
                new ObjectParameter("Solicitud_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_API_RodalDescuentoPoligono_Result>("[db_RNF_APIEntities].[fc_API_RodalDescuentoPoligono](@Solicitud_id)", solicitud_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_API_Sol_Finca_Rodal_Planos")]
        public virtual IQueryable<fc_API_Sol_Finca_Rodal_Planos_Result> fc_API_Sol_Finca_Rodal_Planos(Nullable<long> solicitud_id, Nullable<long> finca_id, Nullable<int> tipo_de_Area, Nullable<long> rodal_id)
        {
            var solicitud_idParameter = solicitud_id.HasValue ?
                new ObjectParameter("Solicitud_id", solicitud_id) :
                new ObjectParameter("Solicitud_id", typeof(long));
    
            var finca_idParameter = finca_id.HasValue ?
                new ObjectParameter("Finca_id", finca_id) :
                new ObjectParameter("Finca_id", typeof(long));
    
            var tipo_de_AreaParameter = tipo_de_Area.HasValue ?
                new ObjectParameter("Tipo_de_Area", tipo_de_Area) :
                new ObjectParameter("Tipo_de_Area", typeof(int));
    
            var rodal_idParameter = rodal_id.HasValue ?
                new ObjectParameter("Rodal_id", rodal_id) :
                new ObjectParameter("Rodal_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_API_Sol_Finca_Rodal_Planos_Result>("[db_RNF_APIEntities].[fc_API_Sol_Finca_Rodal_Planos](@Solicitud_id, @Finca_id, @Tipo_de_Area, @Rodal_id)", solicitud_idParameter, finca_idParameter, tipo_de_AreaParameter, rodal_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_API_Sol_Sel_Rodal_ValidacionesDiametrica")]
        public virtual IQueryable<fc_API_Sol_Sel_Rodal_ValidacionesDiametrica_Result> fc_API_Sol_Sel_Rodal_ValidacionesDiametrica(Nullable<long> solicitud_id, Nullable<long> finca_id)
        {
            var solicitud_idParameter = solicitud_id.HasValue ?
                new ObjectParameter("Solicitud_id", solicitud_id) :
                new ObjectParameter("Solicitud_id", typeof(long));
    
            var finca_idParameter = finca_id.HasValue ?
                new ObjectParameter("Finca_id", finca_id) :
                new ObjectParameter("Finca_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_API_Sol_Sel_Rodal_ValidacionesDiametrica_Result>("[db_RNF_APIEntities].[fc_API_Sol_Sel_Rodal_ValidacionesDiametrica](@Solicitud_id, @Finca_id)", solicitud_idParameter, finca_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_API_Sol_Sel_Rodal_ValidacionesDiametrica_FS")]
        public virtual IQueryable<fc_API_Sol_Sel_Rodal_ValidacionesDiametrica_FS_Result> fc_API_Sol_Sel_Rodal_ValidacionesDiametrica_FS(Nullable<long> solicitud_id)
        {
            var solicitud_idParameter = solicitud_id.HasValue ?
                new ObjectParameter("Solicitud_id", solicitud_id) :
                new ObjectParameter("Solicitud_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_API_Sol_Sel_Rodal_ValidacionesDiametrica_FS_Result>("[db_RNF_APIEntities].[fc_API_Sol_Sel_Rodal_ValidacionesDiametrica_FS](@Solicitud_id)", solicitud_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_API_Sol_Sel_Rodal_ValidacionesDiametrica_PV")]
        public virtual IQueryable<fc_API_Sol_Sel_Rodal_ValidacionesDiametrica_PV_Result> fc_API_Sol_Sel_Rodal_ValidacionesDiametrica_PV(Nullable<long> solicitud_id)
        {
            var solicitud_idParameter = solicitud_id.HasValue ?
                new ObjectParameter("Solicitud_id", solicitud_id) :
                new ObjectParameter("Solicitud_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_API_Sol_Sel_Rodal_ValidacionesDiametrica_PV_Result>("[db_RNF_APIEntities].[fc_API_Sol_Sel_Rodal_ValidacionesDiametrica_PV](@Solicitud_id)", solicitud_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_API_Sol_Sel_Rodal_ValidacionesDiametrica_PV_20221130")]
        public virtual IQueryable<fc_API_Sol_Sel_Rodal_ValidacionesDiametrica_PV_20221130_Result> fc_API_Sol_Sel_Rodal_ValidacionesDiametrica_PV_20221130(Nullable<long> solicitud_id)
        {
            var solicitud_idParameter = solicitud_id.HasValue ?
                new ObjectParameter("Solicitud_id", solicitud_id) :
                new ObjectParameter("Solicitud_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_API_Sol_Sel_Rodal_ValidacionesDiametrica_PV_20221130_Result>("[db_RNF_APIEntities].[fc_API_Sol_Sel_Rodal_ValidacionesDiametrica_PV_20221130](@Solicitud_id)", solicitud_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_API_Sol_Sel_RodalAreProtegidaPoligono")]
        public virtual IQueryable<fc_API_Sol_Sel_RodalAreProtegidaPoligono_Result> fc_API_Sol_Sel_RodalAreProtegidaPoligono(Nullable<long> rodal_id, Nullable<int> solicitud_id)
        {
            var rodal_idParameter = rodal_id.HasValue ?
                new ObjectParameter("Rodal_id", rodal_id) :
                new ObjectParameter("Rodal_id", typeof(long));
    
            var solicitud_idParameter = solicitud_id.HasValue ?
                new ObjectParameter("Solicitud_id", solicitud_id) :
                new ObjectParameter("Solicitud_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_API_Sol_Sel_RodalAreProtegidaPoligono_Result>("[db_RNF_APIEntities].[fc_API_Sol_Sel_RodalAreProtegidaPoligono](@Rodal_id, @Solicitud_id)", rodal_idParameter, solicitud_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_API_Sol_Sel_RodalRegionPoligono")]
        public virtual IQueryable<fc_API_Sol_Sel_RodalRegionPoligono_Result> fc_API_Sol_Sel_RodalRegionPoligono(Nullable<long> rodal_id, Nullable<int> solicitud_id)
        {
            var rodal_idParameter = rodal_id.HasValue ?
                new ObjectParameter("Rodal_id", rodal_id) :
                new ObjectParameter("Rodal_id", typeof(long));
    
            var solicitud_idParameter = solicitud_id.HasValue ?
                new ObjectParameter("Solicitud_id", solicitud_id) :
                new ObjectParameter("Solicitud_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_API_Sol_Sel_RodalRegionPoligono_Result>("[db_RNF_APIEntities].[fc_API_Sol_Sel_RodalRegionPoligono](@Rodal_id, @Solicitud_id)", rodal_idParameter, solicitud_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_Reporte_Auditorias")]
        public virtual IQueryable<fc_Reporte_Auditorias_Result> fc_Reporte_Auditorias(string guid_id)
        {
            var guid_idParameter = guid_id != null ?
                new ObjectParameter("Guid_id", guid_id) :
                new ObjectParameter("Guid_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_Reporte_Auditorias_Result>("[db_RNF_APIEntities].[fc_Reporte_Auditorias](@Guid_id)", guid_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_Reporte_Auditorias_Arboles_DiferenteAnio_Establecimiento")]
        public virtual IQueryable<fc_Reporte_Auditorias_Arboles_DiferenteAnio_Establecimiento_Result> fc_Reporte_Auditorias_Arboles_DiferenteAnio_Establecimiento(string auditoria_id)
        {
            var auditoria_idParameter = auditoria_id != null ?
                new ObjectParameter("Auditoria_id", auditoria_id) :
                new ObjectParameter("Auditoria_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_Reporte_Auditorias_Arboles_DiferenteAnio_Establecimiento_Result>("[db_RNF_APIEntities].[fc_Reporte_Auditorias_Arboles_DiferenteAnio_Establecimiento](@Auditoria_id)", auditoria_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_Reporte_Auditorias_Arboles_DiferenteClase_y_EstadoFitosanitario")]
        public virtual IQueryable<fc_Reporte_Auditorias_Arboles_DiferenteClase_y_EstadoFitosanitario_Result> fc_Reporte_Auditorias_Arboles_DiferenteClase_y_EstadoFitosanitario(string auditoria_id)
        {
            var auditoria_idParameter = auditoria_id != null ?
                new ObjectParameter("Auditoria_id", auditoria_id) :
                new ObjectParameter("Auditoria_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_Reporte_Auditorias_Arboles_DiferenteClase_y_EstadoFitosanitario_Result>("[db_RNF_APIEntities].[fc_Reporte_Auditorias_Arboles_DiferenteClase_y_EstadoFitosanitario](@Auditoria_id)", auditoria_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_Reporte_Auditorias_Arboles_DiferenteDAP_y_Altura")]
        public virtual IQueryable<fc_Reporte_Auditorias_Arboles_DiferenteDAP_y_Altura_Result> fc_Reporte_Auditorias_Arboles_DiferenteDAP_y_Altura(string auditoria_id)
        {
            var auditoria_idParameter = auditoria_id != null ?
                new ObjectParameter("Auditoria_id", auditoria_id) :
                new ObjectParameter("Auditoria_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_Reporte_Auditorias_Arboles_DiferenteDAP_y_Altura_Result>("[db_RNF_APIEntities].[fc_Reporte_Auditorias_Arboles_DiferenteDAP_y_Altura](@Auditoria_id)", auditoria_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_Reporte_Auditorias_Arboles_DiferenteEspecie")]
        public virtual IQueryable<fc_Reporte_Auditorias_Arboles_DiferenteEspecie_Result> fc_Reporte_Auditorias_Arboles_DiferenteEspecie(string auditoria_id)
        {
            var auditoria_idParameter = auditoria_id != null ?
                new ObjectParameter("Auditoria_id", auditoria_id) :
                new ObjectParameter("Auditoria_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_Reporte_Auditorias_Arboles_DiferenteEspecie_Result>("[db_RNF_APIEntities].[fc_Reporte_Auditorias_Arboles_DiferenteEspecie](@Auditoria_id)", auditoria_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_Reporte_Auditorias_Arboles_PromedioDAP_y_Altura")]
        public virtual IQueryable<fc_Reporte_Auditorias_Arboles_PromedioDAP_y_Altura_Result> fc_Reporte_Auditorias_Arboles_PromedioDAP_y_Altura(string auditoria_id)
        {
            var auditoria_idParameter = auditoria_id != null ?
                new ObjectParameter("Auditoria_id", auditoria_id) :
                new ObjectParameter("Auditoria_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_Reporte_Auditorias_Arboles_PromedioDAP_y_Altura_Result>("[db_RNF_APIEntities].[fc_Reporte_Auditorias_Arboles_PromedioDAP_y_Altura](@Auditoria_id)", auditoria_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_Reporte_Auditorias_ArbolesNuevos_PromedioDAP_y_Altura")]
        public virtual IQueryable<fc_Reporte_Auditorias_ArbolesNuevos_PromedioDAP_y_Altura_Result> fc_Reporte_Auditorias_ArbolesNuevos_PromedioDAP_y_Altura(string auditoria_id)
        {
            var auditoria_idParameter = auditoria_id != null ?
                new ObjectParameter("Auditoria_id", auditoria_id) :
                new ObjectParameter("Auditoria_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_Reporte_Auditorias_ArbolesNuevos_PromedioDAP_y_Altura_Result>("[db_RNF_APIEntities].[fc_Reporte_Auditorias_ArbolesNuevos_PromedioDAP_y_Altura](@Auditoria_id)", auditoria_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_Reporte_Auditorias_ArbolesNuevosAgrupados_PromedioDAP_y_Altura")]
        public virtual IQueryable<fc_Reporte_Auditorias_ArbolesNuevosAgrupados_PromedioDAP_y_Altura_Result> fc_Reporte_Auditorias_ArbolesNuevosAgrupados_PromedioDAP_y_Altura(string auditoria_id)
        {
            var auditoria_idParameter = auditoria_id != null ?
                new ObjectParameter("Auditoria_id", auditoria_id) :
                new ObjectParameter("Auditoria_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_Reporte_Auditorias_ArbolesNuevosAgrupados_PromedioDAP_y_Altura_Result>("[db_RNF_APIEntities].[fc_Reporte_Auditorias_ArbolesNuevosAgrupados_PromedioDAP_y_Altura](@Auditoria_id)", auditoria_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_Reporte_Auditorias_Descuento_RodalPoligonoPlano")]
        public virtual IQueryable<fc_Reporte_Auditorias_Descuento_RodalPoligonoPlano_Result> fc_Reporte_Auditorias_Descuento_RodalPoligonoPlano(string auditoria_id, Nullable<long> finca_id, Nullable<long> rodal_id)
        {
            var auditoria_idParameter = auditoria_id != null ?
                new ObjectParameter("Auditoria_id", auditoria_id) :
                new ObjectParameter("Auditoria_id", typeof(string));
    
            var finca_idParameter = finca_id.HasValue ?
                new ObjectParameter("Finca_id", finca_id) :
                new ObjectParameter("Finca_id", typeof(long));
    
            var rodal_idParameter = rodal_id.HasValue ?
                new ObjectParameter("Rodal_id", rodal_id) :
                new ObjectParameter("Rodal_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_Reporte_Auditorias_Descuento_RodalPoligonoPlano_Result>("[db_RNF_APIEntities].[fc_Reporte_Auditorias_Descuento_RodalPoligonoPlano](@Auditoria_id, @Finca_id, @Rodal_id)", auditoria_idParameter, finca_idParameter, rodal_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_Reporte_Auditorias_Sel_FincaPoligonoPlano")]
        public virtual IQueryable<fc_Reporte_Auditorias_Sel_FincaPoligonoPlano_Result> fc_Reporte_Auditorias_Sel_FincaPoligonoPlano(Nullable<long> solicitud_id, Nullable<long> finca_id)
        {
            var solicitud_idParameter = solicitud_id.HasValue ?
                new ObjectParameter("Solicitud_id", solicitud_id) :
                new ObjectParameter("Solicitud_id", typeof(long));
    
            var finca_idParameter = finca_id.HasValue ?
                new ObjectParameter("Finca_id", finca_id) :
                new ObjectParameter("Finca_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_Reporte_Auditorias_Sel_FincaPoligonoPlano_Result>("[db_RNF_APIEntities].[fc_Reporte_Auditorias_Sel_FincaPoligonoPlano](@Solicitud_id, @Finca_id)", solicitud_idParameter, finca_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_Reporte_Auditorias_Sel_RodalPoligono")]
        public virtual IQueryable<fc_Reporte_Auditorias_Sel_RodalPoligono_Result> fc_Reporte_Auditorias_Sel_RodalPoligono(Nullable<long> solicitud_id, Nullable<long> rodal_id)
        {
            var solicitud_idParameter = solicitud_id.HasValue ?
                new ObjectParameter("Solicitud_id", solicitud_id) :
                new ObjectParameter("Solicitud_id", typeof(long));
    
            var rodal_idParameter = rodal_id.HasValue ?
                new ObjectParameter("Rodal_id", rodal_id) :
                new ObjectParameter("Rodal_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_Reporte_Auditorias_Sel_RodalPoligono_Result>("[db_RNF_APIEntities].[fc_Reporte_Auditorias_Sel_RodalPoligono](@Solicitud_id, @Rodal_id)", solicitud_idParameter, rodal_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_Reporte_Auditorias_Sel_RodalPoligonoPlano")]
        public virtual IQueryable<fc_Reporte_Auditorias_Sel_RodalPoligonoPlano_Result> fc_Reporte_Auditorias_Sel_RodalPoligonoPlano(Nullable<long> solicitud_id, Nullable<long> finca_id, Nullable<long> rodal_id, Nullable<int> tipo)
        {
            var solicitud_idParameter = solicitud_id.HasValue ?
                new ObjectParameter("Solicitud_id", solicitud_id) :
                new ObjectParameter("Solicitud_id", typeof(long));
    
            var finca_idParameter = finca_id.HasValue ?
                new ObjectParameter("Finca_id", finca_id) :
                new ObjectParameter("Finca_id", typeof(long));
    
            var rodal_idParameter = rodal_id.HasValue ?
                new ObjectParameter("Rodal_id", rodal_id) :
                new ObjectParameter("Rodal_id", typeof(long));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_Reporte_Auditorias_Sel_RodalPoligonoPlano_Result>("[db_RNF_APIEntities].[fc_Reporte_Auditorias_Sel_RodalPoligonoPlano](@Solicitud_id, @Finca_id, @Rodal_id, @Tipo)", solicitud_idParameter, finca_idParameter, rodal_idParameter, tipoParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_Reporte_Auditorias_Sel_RodalPoligonoPlano_20221114")]
        public virtual IQueryable<fc_Reporte_Auditorias_Sel_RodalPoligonoPlano_20221114_Result> fc_Reporte_Auditorias_Sel_RodalPoligonoPlano_20221114(Nullable<long> solicitud_id, Nullable<long> finca_id, Nullable<long> rodal_id, Nullable<int> tipo)
        {
            var solicitud_idParameter = solicitud_id.HasValue ?
                new ObjectParameter("Solicitud_id", solicitud_id) :
                new ObjectParameter("Solicitud_id", typeof(long));
    
            var finca_idParameter = finca_id.HasValue ?
                new ObjectParameter("Finca_id", finca_id) :
                new ObjectParameter("Finca_id", typeof(long));
    
            var rodal_idParameter = rodal_id.HasValue ?
                new ObjectParameter("Rodal_id", rodal_id) :
                new ObjectParameter("Rodal_id", typeof(long));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_Reporte_Auditorias_Sel_RodalPoligonoPlano_20221114_Result>("[db_RNF_APIEntities].[fc_Reporte_Auditorias_Sel_RodalPoligonoPlano_20221114](@Solicitud_id, @Finca_id, @Rodal_id, @Tipo)", solicitud_idParameter, finca_idParameter, rodal_idParameter, tipoParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_Reporte_Auditorias_Sel_RodalPoligonoPlano_Local")]
        public virtual IQueryable<fc_Reporte_Auditorias_Sel_RodalPoligonoPlano_Local_Result> fc_Reporte_Auditorias_Sel_RodalPoligonoPlano_Local(Nullable<long> solicitud_id, Nullable<long> rodal_id)
        {
            var solicitud_idParameter = solicitud_id.HasValue ?
                new ObjectParameter("Solicitud_id", solicitud_id) :
                new ObjectParameter("Solicitud_id", typeof(long));
    
            var rodal_idParameter = rodal_id.HasValue ?
                new ObjectParameter("Rodal_id", rodal_id) :
                new ObjectParameter("Rodal_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_Reporte_Auditorias_Sel_RodalPoligonoPlano_Local_Result>("[db_RNF_APIEntities].[fc_Reporte_Auditorias_Sel_RodalPoligonoPlano_Local](@Solicitud_id, @Rodal_id)", solicitud_idParameter, rodal_idParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_Reporte_Auditorias_Sel_RodalPoligonoPlano_Resumen")]
        public virtual IQueryable<fc_Reporte_Auditorias_Sel_RodalPoligonoPlano_Resumen_Result> fc_Reporte_Auditorias_Sel_RodalPoligonoPlano_Resumen(Nullable<long> solicitud_id, Nullable<long> finca_id, Nullable<long> rodal_id, Nullable<int> tipo)
        {
            var solicitud_idParameter = solicitud_id.HasValue ?
                new ObjectParameter("Solicitud_id", solicitud_id) :
                new ObjectParameter("Solicitud_id", typeof(long));
    
            var finca_idParameter = finca_id.HasValue ?
                new ObjectParameter("Finca_id", finca_id) :
                new ObjectParameter("Finca_id", typeof(long));
    
            var rodal_idParameter = rodal_id.HasValue ?
                new ObjectParameter("Rodal_id", rodal_id) :
                new ObjectParameter("Rodal_id", typeof(long));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_Reporte_Auditorias_Sel_RodalPoligonoPlano_Resumen_Result>("[db_RNF_APIEntities].[fc_Reporte_Auditorias_Sel_RodalPoligonoPlano_Resumen](@Solicitud_id, @Finca_id, @Rodal_id, @Tipo)", solicitud_idParameter, finca_idParameter, rodal_idParameter, tipoParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_Reporte_Auditorias_Sel_RodalPoligonoPlanoTecnicoOUsuario")]
        public virtual IQueryable<fc_Reporte_Auditorias_Sel_RodalPoligonoPlanoTecnicoOUsuario_Result> fc_Reporte_Auditorias_Sel_RodalPoligonoPlanoTecnicoOUsuario(Nullable<long> solicitud_id, Nullable<long> finca_id, Nullable<long> rodal_id, Nullable<int> tipo, Nullable<bool> tecnico, Nullable<bool> usuario)
        {
            var solicitud_idParameter = solicitud_id.HasValue ?
                new ObjectParameter("Solicitud_id", solicitud_id) :
                new ObjectParameter("Solicitud_id", typeof(long));
    
            var finca_idParameter = finca_id.HasValue ?
                new ObjectParameter("Finca_id", finca_id) :
                new ObjectParameter("Finca_id", typeof(long));
    
            var rodal_idParameter = rodal_id.HasValue ?
                new ObjectParameter("Rodal_id", rodal_id) :
                new ObjectParameter("Rodal_id", typeof(long));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(int));
    
            var tecnicoParameter = tecnico.HasValue ?
                new ObjectParameter("Tecnico", tecnico) :
                new ObjectParameter("Tecnico", typeof(bool));
    
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_Reporte_Auditorias_Sel_RodalPoligonoPlanoTecnicoOUsuario_Result>("[db_RNF_APIEntities].[fc_Reporte_Auditorias_Sel_RodalPoligonoPlanoTecnicoOUsuario](@Solicitud_id, @Finca_id, @Rodal_id, @Tipo, @Tecnico, @Usuario)", solicitud_idParameter, finca_idParameter, rodal_idParameter, tipoParameter, tecnicoParameter, usuarioParameter);
        }
    
        [DbFunction("db_RNF_APIEntities", "fc_Rerporte_Auditorias_Finca_Rodal_Planos")]
        public virtual IQueryable<fc_Rerporte_Auditorias_Finca_Rodal_Planos_Result> fc_Rerporte_Auditorias_Finca_Rodal_Planos(Nullable<long> solicitud_id, Nullable<long> finca_id, Nullable<long> rodal_id)
        {
            var solicitud_idParameter = solicitud_id.HasValue ?
                new ObjectParameter("Solicitud_id", solicitud_id) :
                new ObjectParameter("Solicitud_id", typeof(long));
    
            var finca_idParameter = finca_id.HasValue ?
                new ObjectParameter("Finca_id", finca_id) :
                new ObjectParameter("Finca_id", typeof(long));
    
            var rodal_idParameter = rodal_id.HasValue ?
                new ObjectParameter("Rodal_id", rodal_id) :
                new ObjectParameter("Rodal_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_Rerporte_Auditorias_Finca_Rodal_Planos_Result>("[db_RNF_APIEntities].[fc_Rerporte_Auditorias_Finca_Rodal_Planos](@Solicitud_id, @Finca_id, @Rodal_id)", solicitud_idParameter, finca_idParameter, rodal_idParameter);
        }
    
        public virtual int BuscaValorEnBBDD(string strValorBusqueda)
        {
            var strValorBusquedaParameter = strValorBusqueda != null ?
                new ObjectParameter("StrValorBusqueda", strValorBusqueda) :
                new ObjectParameter("StrValorBusqueda", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BuscaValorEnBBDD", strValorBusquedaParameter);
        }
    
        public virtual int SP_API_Limpiar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_API_Limpiar");
        }
    }
}
