//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_RNF_IntermediaEntities : DbContext
    {
        public db_RNF_IntermediaEntities()
            : base("name=db_RNF_IntermediaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_API_Categoria_Intermedia> Tbl_API_Categoria_Intermedia { get; set; }
        public virtual DbSet<Tbl_API_ExpedienteOficio_FasePermitida> Tbl_API_ExpedienteOficio_FasePermitida { get; set; }
        public virtual DbSet<Tbl_API_PinpepOld_EspeciesForestales> Tbl_API_PinpepOld_EspeciesForestales { get; set; }
        public virtual DbSet<Tbl_API_PinpepOld_Expediente> Tbl_API_PinpepOld_Expediente { get; set; }
        public virtual DbSet<Tbl_API_PinpepOld_Finca> Tbl_API_PinpepOld_Finca { get; set; }
        public virtual DbSet<Tbl_API_PinpepOld_InformeTecnico> Tbl_API_PinpepOld_InformeTecnico { get; set; }
        public virtual DbSet<Tbl_API_PinpepOld_Propietarios> Tbl_API_PinpepOld_Propietarios { get; set; }
        public virtual DbSet<Tbl_API_PinpepOld_PropietariosGrupal> Tbl_API_PinpepOld_PropietariosGrupal { get; set; }
        public virtual DbSet<Tbl_API_PinpepOld_Representante> Tbl_API_PinpepOld_Representante { get; set; }
        public virtual DbSet<Tbl_API_PinpepOld_Rodales> Tbl_API_PinpepOld_Rodales { get; set; }
        public virtual DbSet<Tbl_API_PinpepOld_Rodales_Poligonos> Tbl_API_PinpepOld_Rodales_Poligonos { get; set; }
        public virtual DbSet<Tbl_API_PinpepOld_Rodales_PoligonosDescuento> Tbl_API_PinpepOld_Rodales_PoligonosDescuento { get; set; }
        public virtual DbSet<Tbl_API_Probosque_EspeciesForestales> Tbl_API_Probosque_EspeciesForestales { get; set; }
        public virtual DbSet<Tbl_API_Probosque_Expediente> Tbl_API_Probosque_Expediente { get; set; }
        public virtual DbSet<Tbl_API_Probosque_Finca> Tbl_API_Probosque_Finca { get; set; }
        public virtual DbSet<Tbl_API_Probosque_FincaRegistroPropiedad> Tbl_API_Probosque_FincaRegistroPropiedad { get; set; }
        public virtual DbSet<Tbl_API_Probosque_InformeTecnico> Tbl_API_Probosque_InformeTecnico { get; set; }
        public virtual DbSet<Tbl_API_Probosque_Propietario_PersonaIndividual> Tbl_API_Probosque_Propietario_PersonaIndividual { get; set; }
        public virtual DbSet<Tbl_API_Probosque_Propietario_PersonaJuridica> Tbl_API_Probosque_Propietario_PersonaJuridica { get; set; }
        public virtual DbSet<Tbl_API_Probosque_RepresentanteLegal> Tbl_API_Probosque_RepresentanteLegal { get; set; }
        public virtual DbSet<Tbl_API_Probosque_Rodales> Tbl_API_Probosque_Rodales { get; set; }
        public virtual DbSet<Tbl_API_Probosque_Rodales_Documentos> Tbl_API_Probosque_Rodales_Documentos { get; set; }
        public virtual DbSet<Tbl_API_Probosque_Rodales_Poligonos> Tbl_API_Probosque_Rodales_Poligonos { get; set; }
        public virtual DbSet<Tbl_API_Probosque_Rodales_PoligonosDescuento> Tbl_API_Probosque_Rodales_PoligonosDescuento { get; set; }
        public virtual DbSet<Tbl_Categoria> Tbl_Categoria { get; set; }
    
        public virtual int SP_Limpiar_PinpepOld()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Limpiar_PinpepOld");
        }
    
        public virtual int SP_Limpiar_Probosque()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Limpiar_Probosque");
        }
    
        public virtual int SP_Limpiar_Todo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Limpiar_Todo");
        }
    
        public virtual int SP_MigrarPinpepOld(string expediente, Nullable<int> categoria_id, Nullable<int> sub_Categoria_id, Nullable<int> sub_Sub_Categoria_id, Nullable<int> region_id, Nullable<int> subRegion_id, string dPI_Titular, Nullable<long> usuario_id)
        {
            var expedienteParameter = expediente != null ?
                new ObjectParameter("Expediente", expediente) :
                new ObjectParameter("Expediente", typeof(string));
    
            var categoria_idParameter = categoria_id.HasValue ?
                new ObjectParameter("Categoria_id", categoria_id) :
                new ObjectParameter("Categoria_id", typeof(int));
    
            var sub_Categoria_idParameter = sub_Categoria_id.HasValue ?
                new ObjectParameter("Sub_Categoria_id", sub_Categoria_id) :
                new ObjectParameter("Sub_Categoria_id", typeof(int));
    
            var sub_Sub_Categoria_idParameter = sub_Sub_Categoria_id.HasValue ?
                new ObjectParameter("Sub_Sub_Categoria_id", sub_Sub_Categoria_id) :
                new ObjectParameter("Sub_Sub_Categoria_id", typeof(int));
    
            var region_idParameter = region_id.HasValue ?
                new ObjectParameter("Region_id", region_id) :
                new ObjectParameter("Region_id", typeof(int));
    
            var subRegion_idParameter = subRegion_id.HasValue ?
                new ObjectParameter("SubRegion_id", subRegion_id) :
                new ObjectParameter("SubRegion_id", typeof(int));
    
            var dPI_TitularParameter = dPI_Titular != null ?
                new ObjectParameter("DPI_Titular", dPI_Titular) :
                new ObjectParameter("DPI_Titular", typeof(string));
    
            var usuario_idParameter = usuario_id.HasValue ?
                new ObjectParameter("Usuario_id", usuario_id) :
                new ObjectParameter("Usuario_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MigrarPinpepOld", expedienteParameter, categoria_idParameter, sub_Categoria_idParameter, sub_Sub_Categoria_idParameter, region_idParameter, subRegion_idParameter, dPI_TitularParameter, usuario_idParameter);
        }
    
        public virtual int SP_MigrarPinpepOld_Bck_20230807(string expediente, Nullable<int> categoria_id, Nullable<int> sub_Categoria_id, Nullable<int> sub_Sub_Categoria_id, Nullable<int> region_id, Nullable<int> subRegion_id, string dPI_Titular)
        {
            var expedienteParameter = expediente != null ?
                new ObjectParameter("Expediente", expediente) :
                new ObjectParameter("Expediente", typeof(string));
    
            var categoria_idParameter = categoria_id.HasValue ?
                new ObjectParameter("Categoria_id", categoria_id) :
                new ObjectParameter("Categoria_id", typeof(int));
    
            var sub_Categoria_idParameter = sub_Categoria_id.HasValue ?
                new ObjectParameter("Sub_Categoria_id", sub_Categoria_id) :
                new ObjectParameter("Sub_Categoria_id", typeof(int));
    
            var sub_Sub_Categoria_idParameter = sub_Sub_Categoria_id.HasValue ?
                new ObjectParameter("Sub_Sub_Categoria_id", sub_Sub_Categoria_id) :
                new ObjectParameter("Sub_Sub_Categoria_id", typeof(int));
    
            var region_idParameter = region_id.HasValue ?
                new ObjectParameter("Region_id", region_id) :
                new ObjectParameter("Region_id", typeof(int));
    
            var subRegion_idParameter = subRegion_id.HasValue ?
                new ObjectParameter("SubRegion_id", subRegion_id) :
                new ObjectParameter("SubRegion_id", typeof(int));
    
            var dPI_TitularParameter = dPI_Titular != null ?
                new ObjectParameter("DPI_Titular", dPI_Titular) :
                new ObjectParameter("DPI_Titular", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MigrarPinpepOld_Bck_20230807", expedienteParameter, categoria_idParameter, sub_Categoria_idParameter, sub_Sub_Categoria_idParameter, region_idParameter, subRegion_idParameter, dPI_TitularParameter);
        }
    
        public virtual ObjectResult<SP_MigrarProbosque_Result> SP_MigrarProbosque(string expediente, Nullable<int> categoria_id, Nullable<int> sub_Categoria_id, Nullable<int> sub_Sub_Categoria_id, Nullable<int> region_id, Nullable<int> subRegion_id, string dPI_Titular, Nullable<long> usuario_id)
        {
            var expedienteParameter = expediente != null ?
                new ObjectParameter("Expediente", expediente) :
                new ObjectParameter("Expediente", typeof(string));
    
            var categoria_idParameter = categoria_id.HasValue ?
                new ObjectParameter("Categoria_id", categoria_id) :
                new ObjectParameter("Categoria_id", typeof(int));
    
            var sub_Categoria_idParameter = sub_Categoria_id.HasValue ?
                new ObjectParameter("Sub_Categoria_id", sub_Categoria_id) :
                new ObjectParameter("Sub_Categoria_id", typeof(int));
    
            var sub_Sub_Categoria_idParameter = sub_Sub_Categoria_id.HasValue ?
                new ObjectParameter("Sub_Sub_Categoria_id", sub_Sub_Categoria_id) :
                new ObjectParameter("Sub_Sub_Categoria_id", typeof(int));
    
            var region_idParameter = region_id.HasValue ?
                new ObjectParameter("Region_id", region_id) :
                new ObjectParameter("Region_id", typeof(int));
    
            var subRegion_idParameter = subRegion_id.HasValue ?
                new ObjectParameter("SubRegion_id", subRegion_id) :
                new ObjectParameter("SubRegion_id", typeof(int));
    
            var dPI_TitularParameter = dPI_Titular != null ?
                new ObjectParameter("DPI_Titular", dPI_Titular) :
                new ObjectParameter("DPI_Titular", typeof(string));
    
            var usuario_idParameter = usuario_id.HasValue ?
                new ObjectParameter("Usuario_id", usuario_id) :
                new ObjectParameter("Usuario_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MigrarProbosque_Result>("SP_MigrarProbosque", expedienteParameter, categoria_idParameter, sub_Categoria_idParameter, sub_Sub_Categoria_idParameter, region_idParameter, subRegion_idParameter, dPI_TitularParameter, usuario_idParameter);
        }
    
        public virtual int SP_MigrarProbosque_Bk_20230621_K1(string expediente, Nullable<int> categoria_id, Nullable<int> sub_Categoria_id, Nullable<int> sub_Sub_Categoria_id, Nullable<int> region_id, Nullable<int> subRegion_id, string dPI_Titular)
        {
            var expedienteParameter = expediente != null ?
                new ObjectParameter("Expediente", expediente) :
                new ObjectParameter("Expediente", typeof(string));
    
            var categoria_idParameter = categoria_id.HasValue ?
                new ObjectParameter("Categoria_id", categoria_id) :
                new ObjectParameter("Categoria_id", typeof(int));
    
            var sub_Categoria_idParameter = sub_Categoria_id.HasValue ?
                new ObjectParameter("Sub_Categoria_id", sub_Categoria_id) :
                new ObjectParameter("Sub_Categoria_id", typeof(int));
    
            var sub_Sub_Categoria_idParameter = sub_Sub_Categoria_id.HasValue ?
                new ObjectParameter("Sub_Sub_Categoria_id", sub_Sub_Categoria_id) :
                new ObjectParameter("Sub_Sub_Categoria_id", typeof(int));
    
            var region_idParameter = region_id.HasValue ?
                new ObjectParameter("Region_id", region_id) :
                new ObjectParameter("Region_id", typeof(int));
    
            var subRegion_idParameter = subRegion_id.HasValue ?
                new ObjectParameter("SubRegion_id", subRegion_id) :
                new ObjectParameter("SubRegion_id", typeof(int));
    
            var dPI_TitularParameter = dPI_Titular != null ?
                new ObjectParameter("DPI_Titular", dPI_Titular) :
                new ObjectParameter("DPI_Titular", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MigrarProbosque_Bk_20230621_K1", expedienteParameter, categoria_idParameter, sub_Categoria_idParameter, sub_Sub_Categoria_idParameter, region_idParameter, subRegion_idParameter, dPI_TitularParameter);
        }
    
        public virtual int SP_MiniLimpiarExpediente_Probosque(string expediente)
        {
            var expedienteParameter = expediente != null ?
                new ObjectParameter("Expediente", expediente) :
                new ObjectParameter("Expediente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MiniLimpiarExpediente_Probosque", expedienteParameter);
        }
    }
}
