//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_RNF_SurveyEntities : DbContext
    {
        public db_RNF_SurveyEntities()
            : base("name=db_RNF_SurveyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Enc_Encuesta> Tbl_Enc_Encuesta { get; set; }
        public virtual DbSet<Tbl_Enc_Encuesta_Pregunta> Tbl_Enc_Encuesta_Pregunta { get; set; }
        public virtual DbSet<Tbl_Enc_Encuesta_Respuesta> Tbl_Enc_Encuesta_Respuesta { get; set; }
        public virtual DbSet<Tbl_Enc_EncuestaXCategoria> Tbl_Enc_EncuestaXCategoria { get; set; }
        public virtual DbSet<Tbl_Enc_Tipo_Respuesta> Tbl_Enc_Tipo_Respuesta { get; set; }
        public virtual DbSet<Tbl_EncResp_Encuesta> Tbl_EncResp_Encuesta { get; set; }
        public virtual DbSet<Tbl_EncResp_Encuesta_Documento> Tbl_EncResp_Encuesta_Documento { get; set; }
        public virtual DbSet<Tbl_EncResp_Encuesta_Estado> Tbl_EncResp_Encuesta_Estado { get; set; }
        public virtual DbSet<Tbl_EncResp_Encuesta_Pregunta> Tbl_EncResp_Encuesta_Pregunta { get; set; }
        public virtual DbSet<Tbl_EncResp_Encuesta_PreguntaRespuesta> Tbl_EncResp_Encuesta_PreguntaRespuesta { get; set; }
        public virtual DbSet<Tbl_Web_Formulario> Tbl_Web_Formulario { get; set; }
    
        public virtual ObjectResult<SP_Enc_BajarPregunta_Result> SP_Enc_BajarPregunta(Nullable<int> id_Encuesta, Nullable<int> id_Pregunta)
        {
            var id_EncuestaParameter = id_Encuesta.HasValue ?
                new ObjectParameter("id_Encuesta", id_Encuesta) :
                new ObjectParameter("id_Encuesta", typeof(int));
    
            var id_PreguntaParameter = id_Pregunta.HasValue ?
                new ObjectParameter("id_Pregunta", id_Pregunta) :
                new ObjectParameter("id_Pregunta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Enc_BajarPregunta_Result>("SP_Enc_BajarPregunta", id_EncuestaParameter, id_PreguntaParameter);
        }
    
        public virtual int sp_enc_crate_update_encuesta(Nullable<int> id_encuesta, string descripcion, Nullable<System.DateTime> fecha_inicio, Nullable<System.DateTime> fecha_fin, Nullable<int> empresa, Nullable<int> usuario)
        {
            var id_encuestaParameter = id_encuesta.HasValue ?
                new ObjectParameter("id_encuesta", id_encuesta) :
                new ObjectParameter("id_encuesta", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var fecha_inicioParameter = fecha_inicio.HasValue ?
                new ObjectParameter("fecha_inicio", fecha_inicio) :
                new ObjectParameter("fecha_inicio", typeof(System.DateTime));
    
            var fecha_finParameter = fecha_fin.HasValue ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(System.DateTime));
    
            var empresaParameter = empresa.HasValue ?
                new ObjectParameter("empresa", empresa) :
                new ObjectParameter("empresa", typeof(int));
    
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_enc_crate_update_encuesta", id_encuestaParameter, descripcionParameter, fecha_inicioParameter, fecha_finParameter, empresaParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<SP_Enc_SubirPregunta_Result> SP_Enc_SubirPregunta(Nullable<int> id_Encuesta, Nullable<int> id_Pregunta)
        {
            var id_EncuestaParameter = id_Encuesta.HasValue ?
                new ObjectParameter("id_Encuesta", id_Encuesta) :
                new ObjectParameter("id_Encuesta", typeof(int));
    
            var id_PreguntaParameter = id_Pregunta.HasValue ?
                new ObjectParameter("id_Pregunta", id_Pregunta) :
                new ObjectParameter("id_Pregunta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Enc_SubirPregunta_Result>("SP_Enc_SubirPregunta", id_EncuestaParameter, id_PreguntaParameter);
        }
    
        public virtual ObjectResult<Sp_EncResp_Encuesta_Pregunta_Result> Sp_EncResp_Encuesta_Pregunta(Nullable<int> id_encuesta, Nullable<long> swcreatedby, Nullable<int> id_Correlativo, Nullable<int> id_pregunta, string respuesta_Observaciones, Nullable<long> swupdatedby)
        {
            var id_encuestaParameter = id_encuesta.HasValue ?
                new ObjectParameter("id_encuesta", id_encuesta) :
                new ObjectParameter("id_encuesta", typeof(int));
    
            var swcreatedbyParameter = swcreatedby.HasValue ?
                new ObjectParameter("swcreatedby", swcreatedby) :
                new ObjectParameter("swcreatedby", typeof(long));
    
            var id_CorrelativoParameter = id_Correlativo.HasValue ?
                new ObjectParameter("id_Correlativo", id_Correlativo) :
                new ObjectParameter("id_Correlativo", typeof(int));
    
            var id_preguntaParameter = id_pregunta.HasValue ?
                new ObjectParameter("id_pregunta", id_pregunta) :
                new ObjectParameter("id_pregunta", typeof(int));
    
            var respuesta_ObservacionesParameter = respuesta_Observaciones != null ?
                new ObjectParameter("Respuesta_Observaciones", respuesta_Observaciones) :
                new ObjectParameter("Respuesta_Observaciones", typeof(string));
    
            var swupdatedbyParameter = swupdatedby.HasValue ?
                new ObjectParameter("swupdatedby", swupdatedby) :
                new ObjectParameter("swupdatedby", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_EncResp_Encuesta_Pregunta_Result>("Sp_EncResp_Encuesta_Pregunta", id_encuestaParameter, swcreatedbyParameter, id_CorrelativoParameter, id_preguntaParameter, respuesta_ObservacionesParameter, swupdatedbyParameter);
        }
    
        public virtual ObjectResult<Sp_EncResp_Encuesta_PreguntaEspecifica_Result> Sp_EncResp_Encuesta_PreguntaEspecifica(Nullable<int> id_encuesta, Nullable<long> swcreatedby, Nullable<int> id_Correlativo, Nullable<int> id_pregunta, Nullable<int> id_respuesta, Nullable<bool> aplica, string respuesta_Observaciones, Nullable<long> swupdatedby)
        {
            var id_encuestaParameter = id_encuesta.HasValue ?
                new ObjectParameter("id_encuesta", id_encuesta) :
                new ObjectParameter("id_encuesta", typeof(int));
    
            var swcreatedbyParameter = swcreatedby.HasValue ?
                new ObjectParameter("swcreatedby", swcreatedby) :
                new ObjectParameter("swcreatedby", typeof(long));
    
            var id_CorrelativoParameter = id_Correlativo.HasValue ?
                new ObjectParameter("id_Correlativo", id_Correlativo) :
                new ObjectParameter("id_Correlativo", typeof(int));
    
            var id_preguntaParameter = id_pregunta.HasValue ?
                new ObjectParameter("id_pregunta", id_pregunta) :
                new ObjectParameter("id_pregunta", typeof(int));
    
            var id_respuestaParameter = id_respuesta.HasValue ?
                new ObjectParameter("id_respuesta", id_respuesta) :
                new ObjectParameter("id_respuesta", typeof(int));
    
            var aplicaParameter = aplica.HasValue ?
                new ObjectParameter("Aplica", aplica) :
                new ObjectParameter("Aplica", typeof(bool));
    
            var respuesta_ObservacionesParameter = respuesta_Observaciones != null ?
                new ObjectParameter("Respuesta_Observaciones", respuesta_Observaciones) :
                new ObjectParameter("Respuesta_Observaciones", typeof(string));
    
            var swupdatedbyParameter = swupdatedby.HasValue ?
                new ObjectParameter("swupdatedby", swupdatedby) :
                new ObjectParameter("swupdatedby", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_EncResp_Encuesta_PreguntaEspecifica_Result>("Sp_EncResp_Encuesta_PreguntaEspecifica", id_encuestaParameter, swcreatedbyParameter, id_CorrelativoParameter, id_preguntaParameter, id_respuestaParameter, aplicaParameter, respuesta_ObservacionesParameter, swupdatedbyParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_send_data(string titulo)
        {
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_send_data", tituloParameter);
        }
    }
}
