//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_WhatsappEntities : DbContext
    {
        public db_WhatsappEntities()
            : base("name=db_WhatsappEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Meta_Mensajes> Tbl_Meta_Mensajes { get; set; }
        public virtual DbSet<Tbl_Meta_ParametrosGenerales> Tbl_Meta_ParametrosGenerales { get; set; }
        public virtual DbSet<Tbl_Meta_ValidarTelefono> Tbl_Meta_ValidarTelefono { get; set; }
        public virtual DbSet<Tbl_Seg_Parametros> Tbl_Seg_Parametros { get; set; }
        public virtual DbSet<Tbl_Whatsapp_Mensajes> Tbl_Whatsapp_Mensajes { get; set; }
    
        [DbFunction("db_WhatsappEntities", "Fc_Meta_MensajesPendientesAutorizados")]
        public virtual IQueryable<Fc_Meta_MensajesPendientesAutorizados_Result> Fc_Meta_MensajesPendientesAutorizados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fc_Meta_MensajesPendientesAutorizados_Result>("[db_WhatsappEntities].[Fc_Meta_MensajesPendientesAutorizados]()");
        }
    
        public virtual ObjectResult<SP_Meta_ValidarTelefono_Result> SP_Meta_ValidarTelefono(string telefono_id)
        {
            var telefono_idParameter = telefono_id != null ?
                new ObjectParameter("Telefono_id", telefono_id) :
                new ObjectParameter("Telefono_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Meta_ValidarTelefono_Result>("SP_Meta_ValidarTelefono", telefono_idParameter);
        }
    }
}
