//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personajuridica
    {
        public long PersonaJuridicaId { get; set; }
        public string NombreComercial { get; set; }
        public string RepresentanteNombre { get; set; }
        public string RepresentanteCedula { get; set; }
        public string Nit { get; set; }
        public string DireccionNotificacion { get; set; }
        public string RegNumero { get; set; }
        public string RegFolio { get; set; }
        public string RegLibro { get; set; }
        public int Categoria1Id { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Extension1 { get; set; }
        public string Extension2 { get; set; }
        public string Fax { get; set; }
        public string EMail { get; set; }
        public string DireccionPlanta { get; set; }
        public Nullable<int> MunicipioId { get; set; }
        public Nullable<int> AldeaId { get; set; }
        public int TipoInstitucionId { get; set; }
        public int TipoIndustriaId { get; set; }
        public string ObjetoEmpresa { get; set; }
        public Nullable<int> Elabora { get; set; }
        public Nullable<int> Comercializa { get; set; }
        public Nullable<int> NoTrabAdministrativos { get; set; }
        public Nullable<int> NoTrabCalificados { get; set; }
        public Nullable<int> NoTrabOperPermanentes { get; set; }
        public Nullable<int> NoTrabOperTemporales { get; set; }
        public Nullable<int> NoTrabOtros { get; set; }
        public Nullable<int> NoTurnos { get; set; }
        public Nullable<int> NoDiasAnio { get; set; }
        public Nullable<int> NoMotosierrasVendidasAnualmente { get; set; }
        public string OtroRegistro { get; set; }
        public Nullable<int> RepresentanteCedulaMuniId { get; set; }
        public Nullable<int> Nacional { get; set; }
        public Nullable<int> TipoProduccionId { get; set; }
        public Nullable<int> TipoRiegoId { get; set; }
        public int Categoria2Id { get; set; }
        public int RequiereRegMercantil { get; set; }
        public Nullable<int> EsExportador { get; set; }
        public Nullable<double> Longitud { get; set; }
        public Nullable<double> Latitud { get; set; }
        public Nullable<decimal> GTMX { get; set; }
        public Nullable<decimal> GTMY { get; set; }
    }
}
