//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class region
    {
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> NumeroRegion { get; set; }
        public string NombreRegion { get; set; }
        public Nullable<int> PadreId { get; set; }
        public string NombreDirector { get; set; }
        public string NumeroRomano { get; set; }
        public Nullable<int> SubregionId { get; set; }
    }
}
