//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registro
    {
        public Nullable<int> RegistroId { get; set; }
        public string NoRegistro { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> TipoRegistroId { get; set; }
        public Nullable<long> RegistradorId { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public int EstadoRegistroId { get; set; }
        public Nullable<long> Id { get; set; }
        public string Expediente { get; set; }
        public int Correlativo { get; set; }
        public Nullable<int> SubRegionId { get; set; }
        public Nullable<System.DateTime> FechaUltimaActualizacion { get; set; }
    }
}
