//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_LOCATION
    {
        public int ID_LOCATION { get; set; }
        public string NO_GRAPHIC { get; set; }
        public string ID_GRPHIC { get; set; }
        public Nullable<decimal> X_GMT { get; set; }
        public Nullable<decimal> Y_GMT { get; set; }
        public string AREA { get; set; }
        public string PROPERTY { get; set; }
        public string DPI { get; set; }
        public string REG { get; set; }
        public string AREA_VERIFY { get; set; }
        public string SUBREGION { get; set; }
        public string LON { get; set; }
        public string LAT { get; set; }
        public string COLOR { get; set; }
    }
}
