//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gest_EtapaSolicitud_InformeCircunstanciado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Gest_EtapaSolicitud_InformeCircunstanciado()
        {
            this.Tbl_Gest_EtapaSolicitud_InformeCircunstanciado_Procedimientos = new HashSet<Tbl_Gest_EtapaSolicitud_InformeCircunstanciado_Procedimientos>();
        }
    
        public long Solicitud_id { get; set; }
        public string Parrafo_1 { get; set; }
        public string Parrafo_2 { get; set; }
        public string Parrafo_3 { get; set; }
        public string Parrafo_4 { get; set; }
        public string Parrafo_5 { get; set; }
        public string Parrafo_6 { get; set; }
        public string Parrafo_7 { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public string Solicitud_Guid_id { get; set; }
        public string EtapaSolicitud_Guid_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Gest_EtapaSolicitud_InformeCircunstanciado_Procedimientos> Tbl_Gest_EtapaSolicitud_InformeCircunstanciado_Procedimientos { get; set; }
    }
}
