//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Seg_UsuarioSubRegion
    {
        public int Region_id { get; set; }
        public int SubRegion_id { get; set; }
        public long Usuario_id { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<System.DateTime> swdateUpdated { get; set; }
        public Nullable<long> swUpdatedby { get; set; }
        public Nullable<int> Estado_id { get; set; }
    
        public virtual Tbl_Gral_SubRegion Tbl_Gral_SubRegion { get; set; }
        public virtual Tbl_Seg_Usuario Tbl_Seg_Usuario { get; set; }
    }
}
