//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Seg_Opcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Seg_Opcion()
        {
            this.Tbl_Seg_Privilegio = new HashSet<Tbl_Seg_Privilegio>();
        }
    
        public int Modulo_id { get; set; }
        public int OpcionTipo_id { get; set; }
        public int Opcion_id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> LastState { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<System.DateTime> swdateUpdated { get; set; }
        public Nullable<long> swUpdatedby { get; set; }
        public string FrmNombre { get; set; }
        public string FrmDescripcion { get; set; }
        public Nullable<int> Orden { get; set; }
        public string Explacion_Funcional { get; set; }
        public string href { get; set; }
    
        public virtual Tbl_Seg_Modulo Tbl_Seg_Modulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Seg_Privilegio> Tbl_Seg_Privilegio { get; set; }
    }
}
