//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_Rodal_Dasometrico_Especie_Formula_Id
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Sol_Rodal_Dasometrico_Especie_Formula_Id()
        {
            this.Tbl_RNF_Rodal_Dasometrico_Especie_Formula = new HashSet<Tbl_RNF_Rodal_Dasometrico_Especie_Formula>();
            this.Tbl_Sol_Rodal_Dasometrico_Especie_Formula = new HashSet<Tbl_Sol_Rodal_Dasometrico_Especie_Formula>();
        }
    
        public int RodalDasometricoEspecieFormula_Id { get; set; }
        public string Especie_id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
        public string FormulaSistemas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Rodal_Dasometrico_Especie_Formula> Tbl_RNF_Rodal_Dasometrico_Especie_Formula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Rodal_Dasometrico_Especie_Formula> Tbl_Sol_Rodal_Dasometrico_Especie_Formula { get; set; }
    }
}
