//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_Finca_Secorf
    {
        public long Solicitud_id { get; set; }
        public long Finca_id { get; set; }
        public long Correlativo_id { get; set; }
        public Nullable<decimal> Area { get; set; }
        public string NombreCientifico { get; set; }
        public Nullable<decimal> DPA_Promedio { get; set; }
        public Nullable<decimal> Altura_Promedio { get; set; }
        public Nullable<decimal> Dencidad_ha { get; set; }
        public Nullable<decimal> Volumen_ha { get; set; }
        public Nullable<System.DateTime> Anio_Establecimiento { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
    }
}
