//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gral_ParametrosGenerales
    {
        public int Entidad_id { get; set; }
        public string Direccion_URL { get; set; }
        public string Direccion_URL_Reportes { get; set; }
        public Nullable<int> Longitud_Celular { get; set; }
        public string Menu { get; set; }
        public string MenuVacio { get; set; }
        public Nullable<bool> VisualizarInformacionDesarrollo { get; set; }
        public Nullable<bool> SubRegiona_PermitirModificarRegistroSinRestriccion { get; set; }
        public Nullable<bool> DirectorRegional_PermitirModificarRegistroSinRestriccion { get; set; }
        public Nullable<bool> Administrador_PermitirModificarRegistroSinRestriccion { get; set; }
        public Nullable<int> Dias_PrimerAvisoPrevioVencimiento { get; set; }
        public Nullable<int> Dias_SegundoAvisoPrevioVencimiento { get; set; }
        public Nullable<int> Dias_TercerAvisoPrevioVencimiento { get; set; }
        public Nullable<int> Dias_CuartoAvisoPrevioVencimiento { get; set; }
        public string ContraseniaVisualizacion { get; set; }
    }
}
