//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gral_Cultivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Gral_Cultivo()
        {
            this.Tbl_RNF_Rodal_Cultivo = new HashSet<Tbl_RNF_Rodal_Cultivo>();
            this.Tbl_Sol_Rodal_Cultivo = new HashSet<Tbl_Sol_Rodal_Cultivo>();
            this.Tbl_Sol_Rodal_CultivoTecnico = new HashSet<Tbl_Sol_Rodal_CultivoTecnico>();
        }
    
        public int Cultivo_Id { get; set; }
        public string Nombre_Tecnico { get; set; }
        public string Nombres_Comunes { get; set; }
        public bool Arbol_Frutales { get; set; }
        public bool Cultivo_SilvoPastoril { get; set; }
        public bool Especies_Agricolas_Permanentes { get; set; }
        public bool Especies_Agricolas_Bianuales { get; set; }
        public bool Especies_Mixtas { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Rodal_Cultivo> Tbl_RNF_Rodal_Cultivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Rodal_Cultivo> Tbl_Sol_Rodal_Cultivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Rodal_CultivoTecnico> Tbl_Sol_Rodal_CultivoTecnico { get; set; }
    }
}
