//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RNF_Rep_Propietario
    {
        public string No_Registro { get; set; }
        public string No_Documento { get; set; }
        public string Tipo { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
    }
}
