//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gral_SubRegion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Gral_SubRegion()
        {
            this.Tbl_RNF_Registro = new HashSet<Tbl_RNF_Registro>();
            this.Tbl_Seg_UsuarioSubRegion = new HashSet<Tbl_Seg_UsuarioSubRegion>();
            this.Tbl_Sol_Solicitud = new HashSet<Tbl_Sol_Solicitud>();
        }
    
        public int Region_id { get; set; }
        public int SubRegion_id { get; set; }
        public string No_SubRegion { get; set; }
        public string Nombre_SubRegion { get; set; }
        public Nullable<int> Id_RNF_S { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public bool Estado_id { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
        public Nullable<int> DepartamentoSubRegion_id { get; set; }
        public Nullable<int> MunicipioSubRegion_id { get; set; }
        public Nullable<int> CasillerosubregionId { get; set; }
        public string No_SubRegionCardinal { get; set; }
    
        public virtual Tbl_Gral_Departamento Tbl_Gral_Departamento { get; set; }
        public virtual Tbl_Gral_Municipio Tbl_Gral_Municipio { get; set; }
        public virtual Tbl_Gral_Region Tbl_Gral_Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Registro> Tbl_RNF_Registro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Seg_UsuarioSubRegion> Tbl_Seg_UsuarioSubRegion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Solicitud> Tbl_Sol_Solicitud { get; set; }
    }
}
