//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_API_Probosque_EspeciesForestales
    {
        public string Guid_id { get; set; }
        public long Id { get; set; }
        public long Correlativo_id { get; set; }
        public Nullable<decimal> Area { get; set; }
        public string NombreCientifico { get; set; }
        public Nullable<System.DateTime> FechaPlantacion { get; set; }
        public Nullable<int> CicloDeCorta { get; set; }
        public Nullable<decimal> DensidadFinal { get; set; }
        public Nullable<decimal> DensidadInicial { get; set; }
        public Nullable<decimal> Mixtaje { get; set; }
        public Nullable<decimal> DistanciaES { get; set; }
        public Nullable<decimal> DistanciaEP { get; set; }
        public Nullable<decimal> DensidadActual { get; set; }
        public Nullable<decimal> Supervivencia { get; set; }
        public Nullable<decimal> PlantasSanas { get; set; }
        public Nullable<decimal> PlantacionDPA { get; set; }
        public Nullable<decimal> PlantacionAltura { get; set; }
        public Nullable<decimal> PlantasAfectadas { get; set; }
        public Nullable<decimal> PlantasEnfermedad { get; set; }
        public Nullable<decimal> PlantasFuego { get; set; }
    }
}
