//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RNF_Rodal_DasometricoHistory
    {
        public string No_Registro { get; set; }
        public string No_RegistroLiteral { get; set; }
        public int No_RegistroCorrelativo { get; set; }
        public long Solicitud_id { get; set; }
        public long Finca_id { get; set; }
        public long Rodal_id { get; set; }
        public int Tipo_de_Area { get; set; }
        public long Dasometrico_id { get; set; }
        public Nullable<decimal> Area_Efectiva_Rodal { get; set; }
        public int No_Parcela { get; set; }
        public Nullable<decimal> Area_Muestreada { get; set; }
        public string Especie_Id { get; set; }
        public Nullable<int> Anio_Establecimiento { get; set; }
        public Nullable<decimal> DAP_Promedio { get; set; }
        public Nullable<decimal> Altura_Promedio { get; set; }
        public Nullable<int> Edad_Bosque { get; set; }
        public Nullable<decimal> Densidad_ha { get; set; }
        public Nullable<int> Cantidad_De_Arboles { get; set; }
        public Nullable<decimal> Volumen { get; set; }
        public Nullable<int> EstadoFitosanitario_id { get; set; }
        public bool DeclaracionJurada { get; set; }
        public decimal Perimetro { get; set; }
        public Nullable<int> Perimetro_Dimensional { get; set; }
        public Nullable<decimal> Area_total { get; set; }
        public Nullable<decimal> Clase_I_DAP_Promedio { get; set; }
        public Nullable<decimal> Clase_I_Altura_Promedio { get; set; }
        public Nullable<decimal> Clase_I_Densidad_Promedio { get; set; }
        public Nullable<decimal> Clase_II_DAP_Promedio { get; set; }
        public Nullable<decimal> Clase_II_Altura_Promedio { get; set; }
        public Nullable<decimal> Clase_II_Densidad_Promedio { get; set; }
        public Nullable<decimal> Clase_III_DAP_Promedio { get; set; }
        public Nullable<decimal> Clase_III_Altura_Promedio { get; set; }
        public Nullable<decimal> Clase_III_Densidad_Promedio { get; set; }
        public Nullable<int> Estado_id { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
        public Nullable<decimal> AreaBasal_MetroCuadrado { get; set; }
        public Nullable<decimal> AreaBasal_Hectarea { get; set; }
        public Nullable<decimal> Volumen_MetrosCubicos { get; set; }
        public Nullable<decimal> Volumen_ha { get; set; }
        public string Formula_Volumen_MetrosCubicos { get; set; }
        public string Formula_Volumen_ha { get; set; }
        public string Formula_AreaBasal_MetroCuadrado { get; set; }
        public string Formula_AreaBasal_Hectarea { get; set; }
        public Nullable<int> Clase_id { get; set; }
    }
}
