//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_gest_EtapaRSS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_gest_EtapaRSS()
        {
            this.Tbl_Gest_Etapa_Respuesta = new HashSet<Tbl_Gest_Etapa_Respuesta>();
        }
    
        public int EtapaRSS_id { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionDetallada { get; set; }
        public Nullable<bool> Informar_a_Solicitante { get; set; }
        public Nullable<int> RolOrigen_id { get; set; }
        public Nullable<int> RolDestino_id { get; set; }
        public Nullable<bool> Informar_a_CasilleroElectronico { get; set; }
        public Nullable<int> Informa_a_CasilleroElectronico_TipoNotificacionId { get; set; }
        public Nullable<int> Informa_a_CasilleroElectronico_SistemaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Gest_Etapa_Respuesta> Tbl_Gest_Etapa_Respuesta { get; set; }
    }
}
