//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RNF_TecnicoProfesional
    {
        public string No_Registro { get; set; }
        public string No_RegistroLiteral { get; set; }
        public int No_RegistroCorrelativo { get; set; }
        public long Solicitud_id { get; set; }
        public long Usuario_id { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public Nullable<int> PuebloPertenencia_id { get; set; }
        public Nullable<int> Sexo_id { get; set; }
        public string Telefono_Celular { get; set; }
        public string Telefono_Oficina { get; set; }
        public string Telefono_Oficina_Extension { get; set; }
        public Nullable<int> DocumentoID_Tipo { get; set; }
        public string No_Documento { get; set; }
        public string No_NIT { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public bool Grado_Academico_Tecnico { get; set; }
        public bool Grado_Academico_Profesional { get; set; }
        public string No_Colegiado { get; set; }
        public string Universidad { get; set; }
        public string UniversidadEspecificarCarrera { get; set; }
        public Nullable<int> Profesion_id { get; set; }
        public bool PostGradoMateriaForestal { get; set; }
        public string PostGradoEspecialidad { get; set; }
        public string PostGradoUniversidad { get; set; }
        public string EspecificarCarrera { get; set; }
        public string Diploma_INAB { get; set; }
        public string No_De_Diploma { get; set; }
        public Nullable<int> DepartamentoDPI_id { get; set; }
        public Nullable<int> MunicipioDPI_id { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Municipio_id { get; set; }
        public Nullable<int> Departamento_id { get; set; }
        public string Lugar_Nacimiento { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public string Correo { get; set; }
    
        public virtual Tbl_Gral_Departamento Tbl_Gral_Departamento { get; set; }
        public virtual Tbl_Gral_Departamento Tbl_Gral_Departamento1 { get; set; }
        public virtual Tbl_Gral_DocumentoID_Tipo Tbl_Gral_DocumentoID_Tipo { get; set; }
        public virtual Tbl_Gral_Municipio Tbl_Gral_Municipio { get; set; }
        public virtual Tbl_Gral_Municipio Tbl_Gral_Municipio1 { get; set; }
        public virtual Tbl_Gral_Profesion Tbl_Gral_Profesion { get; set; }
        public virtual Tbl_Gral_PuebloPertenencia Tbl_Gral_PuebloPertenencia { get; set; }
        public virtual Tbl_Gral_Sexo Tbl_Gral_Sexo { get; set; }
        public virtual Tbl_RNF_Registro Tbl_RNF_Registro { get; set; }
    }
}
