//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_ArrendatarioPersonaJuridica
    {
        public long PersonaJuridica_id { get; set; }
        public long Solicitud_id { get; set; }
        public int PersonaJuridicaTipo_Id { get; set; }
        public string Nombre { get; set; }
        public string No_NIT { get; set; }
        public string DireccionEmpresa { get; set; }
        public Nullable<int> DepartamentoEmpresa_id { get; set; }
        public Nullable<int> MunicipioEmpresa_id { get; set; }
        public Nullable<long> UsuarioExterno_id { get; set; }
        public Nullable<bool> Estado_id { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
    
        public virtual Tbl_Gral_Departamento Tbl_Gral_Departamento { get; set; }
        public virtual Tbl_Gral_Municipio Tbl_Gral_Municipio { get; set; }
        public virtual Tbl_Sol_PersonaJuridicaTipo Tbl_Sol_PersonaJuridicaTipo { get; set; }
        public virtual Tbl_Sol_Solicitud Tbl_Sol_Solicitud { get; set; }
    }
}
