//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RNF_Empresa_Entidad_Vivero_Forestal
    {
        public string No_Registro { get; set; }
        public string No_RegistroLiteral { get; set; }
        public int No_RegistroCorrelativo { get; set; }
        public long Solicitud_id { get; set; }
        public long Vivero_Forestal_id { get; set; }
        public string Especie_Id { get; set; }
        public int Produccion_Anual_Plantas { get; set; }
        public string Nombre_Finca { get; set; }
        public int Departamento_Vivero { get; set; }
        public int Municipio_Vivero { get; set; }
        public int Pais_Procedencia { get; set; }
        public string Codigo_RNF { get; set; }
        public string Numero_Nota_Control_Semilla_Certificada { get; set; }
    
        public virtual Tbl_Gral_Departamento Tbl_Gral_Departamento { get; set; }
        public virtual Tbl_Gral_Especie Tbl_Gral_Especie { get; set; }
        public virtual Tbl_Gral_Municipio Tbl_Gral_Municipio { get; set; }
        public virtual Tbl_Gral_Pais Tbl_Gral_Pais { get; set; }
        public virtual Tbl_RNF_Empresa_Entidad Tbl_RNF_Empresa_Entidad { get; set; }
    }
}
