//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RNF_Registro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_RNF_Registro()
        {
            this.Tbl_RNF_ArrendatarioPersonaIndividual = new HashSet<Tbl_RNF_ArrendatarioPersonaIndividual>();
            this.Tbl_RNF_ArrendatarioPersonaJuridica = new HashSet<Tbl_RNF_ArrendatarioPersonaJuridica>();
            this.Tbl_RNF_Motosierra = new HashSet<Tbl_RNF_Motosierra>();
            this.Tbl_RNF_PropietarioPersonaIndividual = new HashSet<Tbl_RNF_PropietarioPersonaIndividual>();
            this.Tbl_RNF_PropietarioPersonaJuridica = new HashSet<Tbl_RNF_PropietarioPersonaJuridica>();
            this.Tbl_RNF_Registro_Reasignacion = new HashSet<Tbl_RNF_Registro_Reasignacion>();
            this.Tbl_RNF_RepresentanteLegal = new HashSet<Tbl_RNF_RepresentanteLegal>();
        }
    
        public string No_Registro { get; set; }
        public string No_RegistroLiteral { get; set; }
        public int No_RegistroCorrelativo { get; set; }
        public string Expediente { get; set; }
        public Nullable<int> Region_id { get; set; }
        public Nullable<int> SubRegion_id { get; set; }
        public Nullable<int> Categoria_id { get; set; }
        public Nullable<int> Sub_Categoria_id { get; set; }
        public Nullable<int> Sub_Sub_Categoria_id { get; set; }
        public string Guid_id { get; set; }
        public Nullable<int> Estado_id { get; set; }
        public Nullable<System.DateTime> Fecha_De_Vencimiento { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
        public Nullable<int> Old_RegistroId_Identity { get; set; }
        public Nullable<int> Old_TipoRegistroId { get; set; }
        public Nullable<int> Old_RegistradorId { get; set; }
        public Nullable<long> UsuarioExterno_id { get; set; }
        public long Solicitud_id { get; set; }
        public string GuidSolicitud_id { get; set; }
        public string DPI_Titular { get; set; }
        public Nullable<decimal> AreaTotalFincas { get; set; }
        public Nullable<int> TipoInactivacion_id { get; set; }
        public string Descripcion_Inactivacion { get; set; }
        public string ResolucionInscripcion { get; set; }
        public Nullable<System.DateTime> ResolucionInscripcionFecha { get; set; }
        public string ResolucionUltimaActualizacion { get; set; }
        public Nullable<System.DateTime> ResolucionUltimaActualizacionFecha { get; set; }
        public string ResolucionUltimaInactivacion { get; set; }
        public Nullable<System.DateTime> ResolucionUltimaInactivacionFecha { get; set; }
        public string ConstanciaFirmada { get; set; }
        public Nullable<decimal> SolicitudTipo_id { get; set; }
        public Nullable<System.DateTime> FechaModificacionDisponible { get; set; }
        public bool Procedencia_Probosque { get; set; }
        public bool Procedencia_PinpepOld { get; set; }
        public bool Procedencia_PinpepNew { get; set; }
        public bool Procedencia_secorf { get; set; }
        public string Procedencia_Expediente { get; set; }
        public string Procedencia_POA { get; set; }
        public string Procedencia_Licencia { get; set; }
        public string Procedencia_Modalidad { get; set; }
        public string Procedencia_Fase { get; set; }
        public string Procedencia_NombreSolicitante { get; set; }
        public string Procedencia_TipoProyecto { get; set; }
        public string Procedencia_InformeTecnico { get; set; }
        public Nullable<System.DateTime> Procedencia_FechaInicioPeriodo { get; set; }
        public Nullable<System.DateTime> Procedencia_FechaFinPeriodo { get; set; }
        public Nullable<System.DateTime> Fecha_Inscripcion { get; set; }
        public Nullable<System.DateTime> Fecha_Actualizacion { get; set; }
        public Nullable<System.DateTime> Fecha_Inactivacion { get; set; }
        public Nullable<int> InactivacionTecnicoTipo_id { get; set; }
        public string Descripcion_InactivacionTecnico { get; set; }
        public Nullable<long> Bitacora_id { get; set; }
        public string Notificacion_Direccion { get; set; }
        public int Notificacion_Municipio_id { get; set; }
        public int Notificacion_Departamento_id { get; set; }
    
        public virtual Tbl_Gral_Region Tbl_Gral_Region { get; set; }
        public virtual Tbl_Gral_SolicitudConfiguracionTipo Tbl_Gral_SolicitudConfiguracionTipo { get; set; }
        public virtual Tbl_Gral_SubRegion Tbl_Gral_SubRegion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_ArrendatarioPersonaIndividual> Tbl_RNF_ArrendatarioPersonaIndividual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_ArrendatarioPersonaJuridica> Tbl_RNF_ArrendatarioPersonaJuridica { get; set; }
        public virtual Tbl_RNF_Empresa_Entidad Tbl_RNF_Empresa_Entidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Motosierra> Tbl_RNF_Motosierra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_PropietarioPersonaIndividual> Tbl_RNF_PropietarioPersonaIndividual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_PropietarioPersonaJuridica> Tbl_RNF_PropietarioPersonaJuridica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Registro_Reasignacion> Tbl_RNF_Registro_Reasignacion { get; set; }
        public virtual Tbl_RNF_Registro_Estado Tbl_RNF_Registro_Estado { get; set; }
        public virtual Tbl_RNF_Registro_Inactivacion_Tipo Tbl_RNF_Registro_Inactivacion_Tipo { get; set; }
        public virtual Tbl_RNF_Registro_InactivacionTecnico_Tipo Tbl_RNF_Registro_InactivacionTecnico_Tipo { get; set; }
        public virtual Tbl_Sol_Solicitud_Categoria Tbl_Sol_Solicitud_Categoria { get; set; }
        public virtual Tbl_Sol_Solicitud_Sub_Categoria Tbl_Sol_Solicitud_Sub_Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_RepresentanteLegal> Tbl_RNF_RepresentanteLegal { get; set; }
        public virtual Tbl_RNF_TecnicoProfesional Tbl_RNF_TecnicoProfesional { get; set; }
    }
}
