//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_API_Probosque_InformeTecnico
    {
        public string Guid_id { get; set; }
        public string UltimaFaseCertificada { get; set; }
        public string NumeroInforme { get; set; }
        public string PDFInforme { get; set; }
        public string PDFInforme_Local { get; set; }
    }
}
