//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Seg_UsuarioDocumentacion
    {
        public long Usuario_id { get; set; }
        public int DocumentoTipo_id { get; set; }
        public int DocumentoCorrelativo_id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> DocumentoVence { get; set; }
        public string NombreDocumento { get; set; }
        public string NombreBase { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
    
        public virtual Tbl_Seg_Usuario Tbl_Seg_Usuario { get; set; }
        public virtual Tbl_Seg_UsuarioDocumentoTipo Tbl_Seg_UsuarioDocumentoTipo { get; set; }
    }
}
