//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_REPEJU_De
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_REPEJU_De()
        {
            this.Tbl_RNF_Empresa_Entidad_Tipo_Registro = new HashSet<Tbl_RNF_Empresa_Entidad_Tipo_Registro>();
            this.Tbl_RNF_Empresa_Entidad_Tipo_Registro1 = new HashSet<Tbl_RNF_Empresa_Entidad_Tipo_Registro>();
            this.Tbl_Sol_Empresa_Entidad_Tipo_Registro = new HashSet<Tbl_Sol_Empresa_Entidad_Tipo_Registro>();
        }
    
        public int REPEJU_De_Id { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Empresa_Entidad_Tipo_Registro> Tbl_RNF_Empresa_Entidad_Tipo_Registro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Empresa_Entidad_Tipo_Registro> Tbl_RNF_Empresa_Entidad_Tipo_Registro1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Empresa_Entidad_Tipo_Registro> Tbl_Sol_Empresa_Entidad_Tipo_Registro { get; set; }
    }
}
