//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gral_Empresa
    {
        public int Empresa_ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> Fch_CierreContable { get; set; }
        public string No_IGSS_Patronal { get; set; }
        public string Departamento { get; set; }
        public string Municipio { get; set; }
        public string Direccion { get; set; }
        public string Colonia { get; set; }
        public string Zona { get; set; }
        public string Telefono { get; set; }
        public string No_Nit { get; set; }
        public string email { get; set; }
        public string Representante_Legal { get; set; }
        public Nullable<double> Cuota_Patronal_IGSS { get; set; }
        public Nullable<double> Cuota_Laboral_IGSS { get; set; }
        public Nullable<double> Cuota_IRTRA { get; set; }
        public Nullable<double> Cuota_INTECAP { get; set; }
        public Nullable<int> Catalogo_Contable { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> SwUpdatedby { get; set; }
        public Nullable<long> SwCreatedby { get; set; }
    }
}
