//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_EncResp_Encuesta_Documento
    {
        public int id_encuesta { get; set; }
        public long swcreatedby { get; set; }
        public int id_Correlativo { get; set; }
        public int id_pregunta { get; set; }
        public int id_CorrelativoDocumento { get; set; }
        public string Documento { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string NombreBase { get; set; }
    
        public virtual Tbl_EncResp_Encuesta_Pregunta Tbl_EncResp_Encuesta_Pregunta { get; set; }
    }
}
