//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_API_Probosque_Rodales_Poligonos
    {
        public string Guid_id { get; set; }
        public long RodalId { get; set; }
        public long PoligonoId { get; set; }
        public long Id { get; set; }
        public long Orden { get; set; }
        public Nullable<decimal> GTMX { get; set; }
        public Nullable<decimal> GTMY { get; set; }
        public Nullable<decimal> Area { get; set; }
    }
}
