//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gest_Etapa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Gest_Etapa()
        {
            this.Tbl_Gest_Etapa_Respuesta = new HashSet<Tbl_Gest_Etapa_Respuesta>();
            this.Tbl_Gest_Etapa_To_doList = new HashSet<Tbl_Gest_Etapa_To_doList>();
            this.Tbl_Gest_EtapaSolicitud = new HashSet<Tbl_Gest_EtapaSolicitud>();
        }
    
        public int Etapa_id { get; set; }
        public decimal EtapaRuta_id { get; set; }
        public Nullable<int> Rol_id { get; set; }
        public string Nombre_Etapa { get; set; }
        public string Url_Formulario { get; set; }
        public bool EtapaInicialRuta { get; set; }
        public string EscalamientoA_Horas { get; set; }
        public string EscalamientoA_Email { get; set; }
        public string EscalamientoA_Telefono { get; set; }
        public string EscalamientoB_Horas { get; set; }
        public string EscalamientoB_Email { get; set; }
        public string EscalamientoB_Telefono { get; set; }
        public string EscalamientoC_Horas { get; set; }
        public string EscalamientoC_Email { get; set; }
        public string EscalamientoC_Telefono { get; set; }
        public bool RevisarQueNoExistanEtapasPreviasActivas { get; set; }
        public string Documentos_RequeridosDescripcion { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
        public bool Respuesta_Explicita { get; set; }
        public string CheckList_Titulo { get; set; }
        public Nullable<int> EtapaRSS_id { get; set; }
        public bool RequiereDocumentos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Gest_Etapa_Respuesta> Tbl_Gest_Etapa_Respuesta { get; set; }
        public virtual Tbl_Gest_EtapaRuta Tbl_Gest_EtapaRuta { get; set; }
        public virtual Tbl_Seg_Rol Tbl_Seg_Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Gest_Etapa_To_doList> Tbl_Gest_Etapa_To_doList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Gest_EtapaSolicitud> Tbl_Gest_EtapaSolicitud { get; set; }
    }
}
