//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Form_Formulario_FirmaElectronica_Estado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Form_Formulario_FirmaElectronica_Estado()
        {
            this.Tbl_Form_Formulario = new HashSet<Tbl_Form_Formulario>();
            this.Tbl_Form_Formulario_FirmaElectronica_Bitacora = new HashSet<Tbl_Form_Formulario_FirmaElectronica_Bitacora>();
        }
    
        public int FirmaElectronica_Estado_id { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Form_Formulario> Tbl_Form_Formulario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Form_Formulario_FirmaElectronica_Bitacora> Tbl_Form_Formulario_FirmaElectronica_Bitacora { get; set; }
    }
}
