//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_PersonaJuridicaTipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Sol_PersonaJuridicaTipo()
        {
            this.Tbl_Sol_ArrendatarioPersonaJuridica = new HashSet<Tbl_Sol_ArrendatarioPersonaJuridica>();
            this.Tbl_Sol_PropietarioPersonaJuridica = new HashSet<Tbl_Sol_PropietarioPersonaJuridica>();
        }
    
        public int PersonaJuridicaTipo_Id { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_ArrendatarioPersonaJuridica> Tbl_Sol_ArrendatarioPersonaJuridica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_PropietarioPersonaJuridica> Tbl_Sol_PropietarioPersonaJuridica { get; set; }
    }
}
