//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gest_Etapa_Respuesta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Gest_Etapa_Respuesta()
        {
            this.Tbl_Gest_Etapa_RespuestaDocumentoTipo = new HashSet<Tbl_Gest_Etapa_RespuestaDocumentoTipo>();
            this.Tbl_Gest_Etapa_RespuestaFormulario = new HashSet<Tbl_Gest_Etapa_RespuestaFormulario>();
            this.Tbl_Gest_Etapa_RespuestaRuta = new HashSet<Tbl_Gest_Etapa_RespuestaRuta>();
        }
    
        public int Etapa_Respuesta_id { get; set; }
        public int Etapa_id { get; set; }
        public decimal EtapaRuta_id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Respuesta_default { get; set; }
        public Nullable<int> Solicitud_Nuevo_Estado_id { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
        public string Icono { get; set; }
        public string ButtonColor { get; set; }
        public Nullable<int> EtapaRSS_id { get; set; }
        public bool RespuestaDeFinalizacion { get; set; }
        public Nullable<int> CantidadIntentos { get; set; }
    
        public virtual Tbl_Gest_Etapa Tbl_Gest_Etapa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Gest_Etapa_RespuestaDocumentoTipo> Tbl_Gest_Etapa_RespuestaDocumentoTipo { get; set; }
        public virtual Tbl_gest_EtapaRSS Tbl_gest_EtapaRSS { get; set; }
        public virtual Tbl_Sol_Solicitud_Estado Tbl_Sol_Solicitud_Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Gest_Etapa_RespuestaFormulario> Tbl_Gest_Etapa_RespuestaFormulario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Gest_Etapa_RespuestaRuta> Tbl_Gest_Etapa_RespuestaRuta { get; set; }
    }
}
