//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gral_SubRegionDepartamento
    {
        public decimal Id_Departamento { get; set; }
        public decimal Id_Municipio { get; set; }
        public string SUBREGION { get; set; }
        public int SubRegion_id { get; set; }
    }
}
