//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BitacoraExcepciones
    {
        public int BitaExce_Id { get; set; }
        public string BitaExce_Expediente { get; set; }
        public string BitaExce_Solicitud { get; set; }
        public string BitaExce_Observacion { get; set; }
        public string BitaExce_UsuarioIngresa { get; set; }
        public Nullable<System.DateTime> BitaExce_FechaRegistro { get; set; }
    }
}
