//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Seg_UsuarioExterno_Dependiente_Perfil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Seg_UsuarioExterno_Dependiente_Perfil()
        {
            this.Tbl_Seg_UsuarioExterno_Dependiente = new HashSet<Tbl_Seg_UsuarioExterno_Dependiente>();
        }
    
        public int Perfil_id { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Seg_UsuarioExterno_Dependiente> Tbl_Seg_UsuarioExterno_Dependiente { get; set; }
    }
}
