//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gral_SolicitudConfiguracionTipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Gral_SolicitudConfiguracionTipo()
        {
            this.Tbl_RNF_Registro = new HashSet<Tbl_RNF_Registro>();
            this.Tbl_RNF_RegistroHistory = new HashSet<Tbl_RNF_RegistroHistory>();
            this.Tbl_Sol_Solicitud = new HashSet<Tbl_Sol_Solicitud>();
        }
    
        public decimal SolicitudTipo_id { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionEnOficio { get; set; }
        public string CobroAsociadoHtml_td { get; set; }
        public Nullable<decimal> AnioVigencia { get; set; }
        public string FormatoSolicitud_Codigo { get; set; }
        public Nullable<System.DateTime> FormatoSolicitud_Fecha { get; set; }
        public string FormatoSolicitud_Version { get; set; }
        public string BoletaDeDecision_Codigo { get; set; }
        public Nullable<System.DateTime> BoletaDeDecision_Fecha { get; set; }
        public string BoletaDeDecision_Version { get; set; }
        public string InformeTecnico_Codigo { get; set; }
        public Nullable<System.DateTime> InformeTecnico_Fecha { get; set; }
        public string InformeTecnico_Version { get; set; }
        public string TipoRegistro { get; set; }
    
        public virtual Tbl_Gral_SolicitudConfiguracion Tbl_Gral_SolicitudConfiguracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Registro> Tbl_RNF_Registro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_RegistroHistory> Tbl_RNF_RegistroHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Solicitud> Tbl_Sol_Solicitud { get; set; }
    }
}
