//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_API_Probosque_FincaRegistroPropiedad
    {
        public string Guid_id { get; set; }
        public Nullable<long> Id { get; set; }
        public string Numero { get; set; }
        public string Folio { get; set; }
        public string Libro { get; set; }
        public string Municipalidad { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> TipoRegistroPropiedad { get; set; }
    }
}
