//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gral_Municipio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Gral_Municipio()
        {
            this.Tbl_RNF_Empresa_Entidad_Vivero_Forestal = new HashSet<Tbl_RNF_Empresa_Entidad_Vivero_Forestal>();
            this.Tbl_Sol_Empresa_Entidad_Vivero_Forestal = new HashSet<Tbl_Sol_Empresa_Entidad_Vivero_Forestal>();
            this.Tbl_Sol_Empresa_Entidad_TecnicoVivero_Forestal = new HashSet<Tbl_Sol_Empresa_Entidad_TecnicoVivero_Forestal>();
            this.Tbl_Sol_Empresa_Entidad_TecnicoVivero_Forestal1 = new HashSet<Tbl_Sol_Empresa_Entidad_TecnicoVivero_Forestal>();
            this.Tbl_Gral_SubRegion = new HashSet<Tbl_Gral_SubRegion>();
            this.Tbl_RNF_ArrendatarioPersonaIndividual = new HashSet<Tbl_RNF_ArrendatarioPersonaIndividual>();
            this.Tbl_RNF_ArrendatarioPersonaJuridica = new HashSet<Tbl_RNF_ArrendatarioPersonaJuridica>();
            this.Tbl_RNF_Empresa_Entidad = new HashSet<Tbl_RNF_Empresa_Entidad>();
            this.Tbl_RNF_Empresa_Entidad1 = new HashSet<Tbl_RNF_Empresa_Entidad>();
            this.Tbl_RNF_Finca = new HashSet<Tbl_RNF_Finca>();
            this.Tbl_RNF_PropietarioPersonaIndividual = new HashSet<Tbl_RNF_PropietarioPersonaIndividual>();
            this.Tbl_RNF_PropietarioPersonaJuridica = new HashSet<Tbl_RNF_PropietarioPersonaJuridica>();
            this.Tbl_RNF_TecnicoProfesional = new HashSet<Tbl_RNF_TecnicoProfesional>();
            this.Tbl_RNF_TecnicoProfesional1 = new HashSet<Tbl_RNF_TecnicoProfesional>();
            this.Tbl_Seg_UsuarioExterno = new HashSet<Tbl_Seg_UsuarioExterno>();
            this.Tbl_Seg_UsuarioExterno1 = new HashSet<Tbl_Seg_UsuarioExterno>();
            this.Tbl_Sol_ArrendatarioPersonaIndividual = new HashSet<Tbl_Sol_ArrendatarioPersonaIndividual>();
            this.Tbl_Sol_ArrendatarioPersonaJuridica = new HashSet<Tbl_Sol_ArrendatarioPersonaJuridica>();
            this.Tbl_Sol_Empresa_Entidad = new HashSet<Tbl_Sol_Empresa_Entidad>();
            this.Tbl_Sol_Empresa_Entidad1 = new HashSet<Tbl_Sol_Empresa_Entidad>();
            this.Tbl_Sol_Finca = new HashSet<Tbl_Sol_Finca>();
            this.Tbl_Sol_PropietarioPersonaIndividual = new HashSet<Tbl_Sol_PropietarioPersonaIndividual>();
            this.Tbl_Sol_PropietarioPersonaJuridica = new HashSet<Tbl_Sol_PropietarioPersonaJuridica>();
            this.Tbl_Sol_Solicitud = new HashSet<Tbl_Sol_Solicitud>();
            this.Tbl_Sol_TecnicoProfesional = new HashSet<Tbl_Sol_TecnicoProfesional>();
            this.Tbl_Sol_TecnicoProfesional1 = new HashSet<Tbl_Sol_TecnicoProfesional>();
        }
    
        public int Municipio_id { get; set; }
        public int Codigo_Municipal { get; set; }
        public string Municipio { get; set; }
        public Nullable<int> Departamento_id { get; set; }
        public Nullable<int> ID_RNF_M { get; set; }
        public Nullable<int> Id_Subregion_RNF { get; set; }
        public Nullable<int> Id_Region_RNF { get; set; }
        public Nullable<decimal> CODREGION { get; set; }
        public Nullable<decimal> CODSUBREGION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Empresa_Entidad_Vivero_Forestal> Tbl_RNF_Empresa_Entidad_Vivero_Forestal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Empresa_Entidad_Vivero_Forestal> Tbl_Sol_Empresa_Entidad_Vivero_Forestal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Empresa_Entidad_TecnicoVivero_Forestal> Tbl_Sol_Empresa_Entidad_TecnicoVivero_Forestal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Empresa_Entidad_TecnicoVivero_Forestal> Tbl_Sol_Empresa_Entidad_TecnicoVivero_Forestal1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Gral_SubRegion> Tbl_Gral_SubRegion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_ArrendatarioPersonaIndividual> Tbl_RNF_ArrendatarioPersonaIndividual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_ArrendatarioPersonaJuridica> Tbl_RNF_ArrendatarioPersonaJuridica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Empresa_Entidad> Tbl_RNF_Empresa_Entidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Empresa_Entidad> Tbl_RNF_Empresa_Entidad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Finca> Tbl_RNF_Finca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_PropietarioPersonaIndividual> Tbl_RNF_PropietarioPersonaIndividual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_PropietarioPersonaJuridica> Tbl_RNF_PropietarioPersonaJuridica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_TecnicoProfesional> Tbl_RNF_TecnicoProfesional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_TecnicoProfesional> Tbl_RNF_TecnicoProfesional1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Seg_UsuarioExterno> Tbl_Seg_UsuarioExterno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Seg_UsuarioExterno> Tbl_Seg_UsuarioExterno1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_ArrendatarioPersonaIndividual> Tbl_Sol_ArrendatarioPersonaIndividual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_ArrendatarioPersonaJuridica> Tbl_Sol_ArrendatarioPersonaJuridica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Empresa_Entidad> Tbl_Sol_Empresa_Entidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Empresa_Entidad> Tbl_Sol_Empresa_Entidad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Finca> Tbl_Sol_Finca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_PropietarioPersonaIndividual> Tbl_Sol_PropietarioPersonaIndividual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_PropietarioPersonaJuridica> Tbl_Sol_PropietarioPersonaJuridica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Solicitud> Tbl_Sol_Solicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_TecnicoProfesional> Tbl_Sol_TecnicoProfesional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_TecnicoProfesional> Tbl_Sol_TecnicoProfesional1 { get; set; }
    }
}
