//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_Solicitud_CategoriaTipoRegistro
    {
        public int TipoRegistroId { get; set; }
        public string TipoRegistro { get; set; }
        public string Abreviatura { get; set; }
        public string CodigoActividad { get; set; }
        public Nullable<int> Categoria_id { get; set; }
        public Nullable<int> Categoria_Sub_id { get; set; }
        public Nullable<int> Categoria_Sub_Sub_id { get; set; }
    }
}
