//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gral_ParametrosGenerales_20211008
    {
        public int Entidad_id { get; set; }
        public string Direccion_URL { get; set; }
        public Nullable<int> Longitud_Celular { get; set; }
        public string Menu { get; set; }
        public string MenuVacio { get; set; }
    }
}
