//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gral_AreaRegion
    {
        public long AreaRegion_Id { get; set; }
        public Nullable<decimal> Longitud_Min { get; set; }
        public Nullable<decimal> Longitud_Max { get; set; }
        public Nullable<decimal> Latitud_Min { get; set; }
        public Nullable<decimal> Latitud_Max { get; set; }
        public string Codigo { get; set; }
        public string CodReg { get; set; }
        public string CodSubReg { get; set; }
        public string Depto { get; set; }
        public Nullable<bool> Estado_id { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
    }
}
