//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gral_SolicitudConfiguracion
    {
        public decimal SolicitudTipo_id { get; set; }
        public Nullable<bool> Usuario_CopiarDesdeRNF { get; set; }
        public Nullable<bool> Usuario_Actualizar { get; set; }
        public Nullable<bool> Usuario_Borrar { get; set; }
        public Nullable<bool> Usuario_Agregar { get; set; }
        public Nullable<bool> Propietario_CopiarDesdeRNF { get; set; }
        public Nullable<bool> Propietario_Editar { get; set; }
        public Nullable<bool> Propietario_Borrar { get; set; }
        public Nullable<bool> Propietario_Agregar { get; set; }
        public Nullable<bool> Representante_CopiarDesdeRNF { get; set; }
        public Nullable<bool> Representante_Editar { get; set; }
        public Nullable<bool> Representante_Borrar { get; set; }
        public Nullable<bool> Representante_Agregar { get; set; }
        public Nullable<bool> Finca_CopiarDesdeRNF { get; set; }
        public Nullable<bool> Finca_Editar { get; set; }
        public Nullable<bool> Finca_Borrar { get; set; }
        public Nullable<bool> Finca_Agregar { get; set; }
        public Nullable<bool> Rodal_CopiarDesdeRNF { get; set; }
        public Nullable<bool> Rodal_Editar { get; set; }
        public Nullable<bool> Rodal_Borrar { get; set; }
        public Nullable<bool> Rodal_Agregar { get; set; }
        public Nullable<bool> Poligono_CopiarDesdeRNF { get; set; }
        public Nullable<bool> Poligono_Agregar { get; set; }
        public Nullable<bool> Cultivo_CopiarDesdeRNF { get; set; }
        public Nullable<bool> Cultivo_Editar { get; set; }
        public Nullable<bool> Cultivo_Borrar { get; set; }
        public Nullable<bool> Cultivo_Agregar { get; set; }
        public Nullable<bool> Dasometricos_CopiarDesdeRNF { get; set; }
        public Nullable<bool> Dasometricos_Agregar { get; set; }
        public Nullable<bool> SubirDocumentos { get; set; }
        public Nullable<bool> Motosierra_CopiarDesdeRNF { get; set; }
        public Nullable<bool> Motosierra_Editar { get; set; }
        public Nullable<bool> Motosierra_Borrar { get; set; }
        public Nullable<bool> Motosierra_Agregar { get; set; }
        public Nullable<bool> Empresa_Entidad_CopiarDesdeRNF { get; set; }
        public Nullable<bool> Empresa_Entidad_Editar { get; set; }
        public Nullable<bool> Empresa_Entidad_Borrar { get; set; }
        public Nullable<bool> Empresa_Entidad_Agregar { get; set; }
    
        public virtual Tbl_Gral_SolicitudConfiguracionTipo Tbl_Gral_SolicitudConfiguracionTipo { get; set; }
    }
}
