//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gral_PuebloPertenencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Gral_PuebloPertenencia()
        {
            this.Tbl_RNF_TecnicoProfesional = new HashSet<Tbl_RNF_TecnicoProfesional>();
            this.Tbl_Seg_UsuarioExterno = new HashSet<Tbl_Seg_UsuarioExterno>();
            this.Tbl_Sol_ArrendatarioPersonaIndividual = new HashSet<Tbl_Sol_ArrendatarioPersonaIndividual>();
            this.Tbl_Sol_PropietarioPersonaIndividual = new HashSet<Tbl_Sol_PropietarioPersonaIndividual>();
            this.Tbl_Sol_TecnicoProfesional = new HashSet<Tbl_Sol_TecnicoProfesional>();
        }
    
        public int Pueblo_id { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_TecnicoProfesional> Tbl_RNF_TecnicoProfesional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Seg_UsuarioExterno> Tbl_Seg_UsuarioExterno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_ArrendatarioPersonaIndividual> Tbl_Sol_ArrendatarioPersonaIndividual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_PropietarioPersonaIndividual> Tbl_Sol_PropietarioPersonaIndividual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_TecnicoProfesional> Tbl_Sol_TecnicoProfesional { get; set; }
    }
}
