//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_API_Sol_Rodal_Dasometrico_Local
    {
        public System.Guid Auditoria_id { get; set; }
        public long Solicitud_id { get; set; }
        public long Finca_id { get; set; }
        public long Rodal_id { get; set; }
        public int No_Parcela { get; set; }
        public long Dasometrico_id { get; set; }
        public string Tipo_de_Area { get; set; }
        public Nullable<bool> Validado { get; set; }
        public Nullable<decimal> Area_Muestreada { get; set; }
        public Nullable<decimal> Area_Efectiva_Rodal { get; set; }
        public string Especie { get; set; }
        public Nullable<int> Anio_Establecimiento { get; set; }
        public Nullable<decimal> DAP_Promedio { get; set; }
        public Nullable<decimal> Altura_Promedio { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public string swtransferedby { get; set; }
        public Nullable<System.DateTime> swdatetransfered { get; set; }
        public Nullable<int> Clase_id { get; set; }
        public string EstadoFitosanitario { get; set; }
        public Nullable<decimal> AreaBasal_MetroCuadrado { get; set; }
        public Nullable<decimal> AreaBasal_Hectarea { get; set; }
        public Nullable<decimal> Volumen_MetrosCubicos { get; set; }
        public Nullable<decimal> Volumen_ha { get; set; }
        public string Formula_Volumen_MetrosCubicos { get; set; }
        public string Formula_Volumen_ha { get; set; }
        public string Formula_AreaBasal_MetroCuadrado { get; set; }
        public string Formula_AreaBasal_Hectarea { get; set; }
        public Nullable<int> Clase_id1 { get; set; }
    }
}
