//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_Finca_PinpepOld_EspeciesProteger
    {
        public long Solicitud_id { get; set; }
        public long Rodal_id { get; set; }
        public Nullable<decimal> Area { get; set; }
        public string EspeciesProteger { get; set; }
        public Nullable<bool> RegistroExterno { get; set; }
    }
}
