//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_Solicitud_Categoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Sol_Solicitud_Categoria()
        {
            this.Tbl_RNF_Registro = new HashSet<Tbl_RNF_Registro>();
            this.Tbl_Sol_DocumentosSolicitar = new HashSet<Tbl_Sol_DocumentosSolicitar>();
            this.Tbl_Sol_Solicitud = new HashSet<Tbl_Sol_Solicitud>();
        }
    
        public int Categoria_id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> EtapaRuta_id_Inicio { get; set; }
        public string CodigoRNF { get; set; }
        public Nullable<bool> Procedencia_Probosque { get; set; }
        public Nullable<bool> Procedencia_PinpepOld { get; set; }
        public Nullable<bool> Procedencia_PinpepNew { get; set; }
        public Nullable<bool> Procedencia_Secorf { get; set; }
        public string Modalidad_Categoria { get; set; }
        public string Modalidad_SubCategoria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Registro> Tbl_RNF_Registro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_DocumentosSolicitar> Tbl_Sol_DocumentosSolicitar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Solicitud> Tbl_Sol_Solicitud { get; set; }
    }
}
