//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_API_Sol_Solicitud
    {
        public System.Guid Auditoria_id { get; set; }
        public Nullable<long> Solicitud_id { get; set; }
        public string Guid_id { get; set; }
        public Nullable<int> Region_id { get; set; }
        public Nullable<int> SubRegion_id { get; set; }
        public string Region { get; set; }
        public string SubRegion { get; set; }
        public string Categoria { get; set; }
        public string SubCategoria { get; set; }
        public string Especificacion { get; set; }
        public string Solicitante { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<long> swusertransferedby { get; set; }
        public string swtransferedby { get; set; }
        public Nullable<System.DateTime> swdatetransfered { get; set; }
    }
}
