//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_EncResp_Encuesta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_EncResp_Encuesta()
        {
            this.Tbl_EncResp_Encuesta_Pregunta = new HashSet<Tbl_EncResp_Encuesta_Pregunta>();
        }
    
        public int id_encuesta { get; set; }
        public long swcreatedby { get; set; }
        public int id_Correlativo { get; set; }
        public string No_Registro { get; set; }
        public string No_RegistroLiteral { get; set; }
        public Nullable<int> No_RegistroCorrelativo { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_final { get; set; }
        public Nullable<int> id_estado { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public string NombreDocumentoFirmado { get; set; }
        public string NombreDocumentoNoFirmado { get; set; }
    
        public virtual Tbl_Enc_Encuesta Tbl_Enc_Encuesta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_EncResp_Encuesta_Pregunta> Tbl_EncResp_Encuesta_Pregunta { get; set; }
        public virtual Tbl_EncResp_Encuesta_Estado Tbl_EncResp_Encuesta_Estado { get; set; }
    }
}
