//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gest_EtapaSolicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Gest_EtapaSolicitud()
        {
            this.Tbl_Gest_EtapaSolicitud_Documento = new HashSet<Tbl_Gest_EtapaSolicitud_Documento>();
            this.Tbl_Gest_EtapaSolicitud_RespuestaDocumentoTipo = new HashSet<Tbl_Gest_EtapaSolicitud_RespuestaDocumentoTipo>();
            this.Tbl_Gest_EtapaSolicitud_RespuestaFormulario = new HashSet<Tbl_Gest_EtapaSolicitud_RespuestaFormulario>();
            this.Tbl_Gest_EtapaSolicitud_To_doList = new HashSet<Tbl_Gest_EtapaSolicitud_To_doList>();
        }
    
        public long Solicitud_id { get; set; }
        public int Etapa_id { get; set; }
        public decimal EtapaRuta_id { get; set; }
        public int CorrelativoEtapa_id { get; set; }
        public Nullable<int> EtapaOrigen_Correlativo_id { get; set; }
        public Nullable<int> Respuesta_id { get; set; }
        public string Motivo { get; set; }
        public Nullable<int> EtapaSolicitudEstado_id { get; set; }
        public Nullable<bool> Escalamiento_A { get; set; }
        public Nullable<bool> Escalamiento_B { get; set; }
        public Nullable<bool> Escalamiento_C { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> swViewedby { get; set; }
        public Nullable<bool> swViewedbyinterno { get; set; }
        public Nullable<System.DateTime> swdateViewed { get; set; }
        public Nullable<long> swLastViewedby { get; set; }
        public Nullable<bool> swLastViewedbyinterno { get; set; }
        public Nullable<System.DateTime> swdateLastViewed { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
        public Nullable<long> UsuarioResponsable_id { get; set; }
        public string EtapaSolicitud_GUID_id { get; set; }
        public string Solicitud_Guid_id { get; set; }
        public string TecnicoOficio { get; set; }
        public string NombreDocumentoFirmado { get; set; }
        public string NombreDocumentoNoFirmado { get; set; }
        public string NoInformeTecnico { get; set; }
        public Nullable<bool> Resolucion_Aprobada { get; set; }
        public Nullable<bool> Resolucion_Denegada { get; set; }
        public string NoResolucion { get; set; }
        public Nullable<bool> Resolucion_Abandono { get; set; }
    
        public virtual Tbl_Gest_Etapa Tbl_Gest_Etapa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Gest_EtapaSolicitud_Documento> Tbl_Gest_EtapaSolicitud_Documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Gest_EtapaSolicitud_RespuestaDocumentoTipo> Tbl_Gest_EtapaSolicitud_RespuestaDocumentoTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Gest_EtapaSolicitud_RespuestaFormulario> Tbl_Gest_EtapaSolicitud_RespuestaFormulario { get; set; }
        public virtual Tbl_Gest_EtapaSolicitudEstado Tbl_Gest_EtapaSolicitudEstado { get; set; }
        public virtual Tbl_Sol_Solicitud Tbl_Sol_Solicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Gest_EtapaSolicitud_To_doList> Tbl_Gest_EtapaSolicitud_To_doList { get; set; }
    }
}
