//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RNF_Registro_Bitacora
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_RNF_Registro_Bitacora()
        {
            this.Tbl_RNF_Registro_BitacoraDocumento = new HashSet<Tbl_RNF_Registro_BitacoraDocumento>();
            this.Tbl_RNF_Registro_BitacoraHallazgo = new HashSet<Tbl_RNF_Registro_BitacoraHallazgo>();
        }
    
        public string No_Registro { get; set; }
        public string No_RegistroLiteral { get; set; }
        public int No_RegistroCorrelativo { get; set; }
        public long Solicitud_id { get; set; }
        public long Bitacora_id { get; set; }
        public Nullable<int> Estado_id { get; set; }
        public string Motivo { get; set; }
        public Nullable<int> Rol_Id_Del_Solicitante { get; set; }
        public Nullable<bool> Inactivar { get; set; }
        public Nullable<bool> Activar { get; set; }
        public Nullable<bool> InactivacionTemporal { get; set; }
        public Nullable<bool> InactivacionDefinitiva { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
        public Nullable<System.DateTime> FechaInicioInactivacionTemporal { get; set; }
        public Nullable<System.DateTime> FechaFinInactivacionTemporal { get; set; }
    
        public virtual Tbl_RNF_Registro_Estado Tbl_RNF_Registro_Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Registro_BitacoraDocumento> Tbl_RNF_Registro_BitacoraDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Registro_BitacoraHallazgo> Tbl_RNF_Registro_BitacoraHallazgo { get; set; }
    }
}
