//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_Solicitud_OficioDictamenJuridico
    {
        public long Solicitud_id { get; set; }
        public bool Dictamen { get; set; }
        public bool Oficio { get; set; }
        public int Etapa_id { get; set; }
        public decimal EtapaRuta_id { get; set; }
        public int CorrelativoEtapa_id { get; set; }
        public string Numero { get; set; }
        public string InicialesDelJuridico { get; set; }
        public string Antecedentes { get; set; }
        public string FundamentoLegal { get; set; }
        public string Analisis { get; set; }
        public string Observaciones { get; set; }
        public string OpinionJuridica { get; set; }
        public string Enmienda_No_1 { get; set; }
        public string Enmienda_No_2 { get; set; }
        public string Enmienda_No_3 { get; set; }
        public string Enmienda_No_4 { get; set; }
        public string Enmienda_No_5 { get; set; }
        public string documentoFirmado { get; set; }
        public string documentoNoFirmado { get; set; }
        public Nullable<int> FirmaElectronicaEstado_id { get; set; }
        public string FirmaElectronicaUsuario { get; set; }
        public string FirmaElectronicaPassword { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<int> FirmaElectronica_Estado_id { get; set; }
        public string EtapaSolicitud_GUID_id { get; set; }
    }
}
