//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_Motosierra
    {
        public long Solicitud_id { get; set; }
        public long Motosierra_id { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Cilindraje { get; set; }
        public string Potencia { get; set; }
        public string No_SerieMotosierra { get; set; }
        public string No_SerieFactura { get; set; }
        public string No_Factura { get; set; }
        public string EmpesaEmisoraFactura { get; set; }
        public string No_Lote { get; set; }
        public string OtroDocumentoRespaldo { get; set; }
        public System.DateTime swdatecreated { get; set; }
        public long swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
    
        public virtual Tbl_Sol_Solicitud Tbl_Sol_Solicitud { get; set; }
    }
}
