//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gral_Pais
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Gral_Pais()
        {
            this.Tbl_RNF_Empresa_Entidad_Vivero_Forestal = new HashSet<Tbl_RNF_Empresa_Entidad_Vivero_Forestal>();
            this.Tbl_Sol_Empresa_Entidad_Vivero_Forestal = new HashSet<Tbl_Sol_Empresa_Entidad_Vivero_Forestal>();
            this.Tbl_Sol_Empresa_Entidad_TecnicoVivero_Forestal = new HashSet<Tbl_Sol_Empresa_Entidad_TecnicoVivero_Forestal>();
        }
    
        public int Pais_id { get; set; }
        public string Pais { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Empresa_Entidad_Vivero_Forestal> Tbl_RNF_Empresa_Entidad_Vivero_Forestal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Empresa_Entidad_Vivero_Forestal> Tbl_Sol_Empresa_Entidad_Vivero_Forestal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Empresa_Entidad_TecnicoVivero_Forestal> Tbl_Sol_Empresa_Entidad_TecnicoVivero_Forestal { get; set; }
    }
}
