//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Cas_CasilleroElectronicoCola
    {
        public string registroId { get; set; }
        public string expediente { get; set; }
        public Nullable<long> casillero { get; set; }
        public Nullable<int> tipoNotificacionId { get; set; }
        public Nullable<int> sistemaId { get; set; }
        public string cui { get; set; }
        public Nullable<int> subregionId { get; set; }
        public string ProcesoQueLaGenero { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<bool> Firmado { get; set; }
        public Nullable<long> Solicitud_id { get; set; }
        public Nullable<int> Etapa_id { get; set; }
        public Nullable<decimal> EtapaRuta_id { get; set; }
        public Nullable<int> CorrelativoEtapa_id { get; set; }
        public Nullable<int> EtapaRSS_id { get; set; }
        public string Respuesta { get; set; }
        public Nullable<int> Intentos { get; set; }
        public Nullable<int> regionId { get; set; }
    }
}
