//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_IdentificadorOficial
    {
        public string IdentificadorAsignado { get; set; }
        public string Codigo { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Version { get; set; }
        public int GestionTipo_id { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<int> Correlativo { get; set; }
        public Nullable<int> Region_id { get; set; }
        public Nullable<int> SubRegion_id { get; set; }
        public Nullable<int> Municipio_id { get; set; }
        public Nullable<int> Departamento_id { get; set; }
        public Nullable<int> Categoria_id { get; set; }
        public Nullable<int> SubCategoria_id { get; set; }
        public Nullable<int> SubSubCategoria_id { get; set; }
        public string CodigoServiciosRNF { get; set; }
        public long Solicitud_id { get; set; }
        public Nullable<int> Etapa_id { get; set; }
        public Nullable<decimal> EtapaRuta_id { get; set; }
        public Nullable<int> CorrelativoEtapa_id { get; set; }
        public string EtapaGuid_id { get; set; }
        public string SolicitudGuid_id { get; set; }
        public Nullable<int> Rol_id { get; set; }
        public Nullable<bool> Firmado { get; set; }
        public Nullable<System.DateTime> swdatecreted { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public string InicialesJuridico { get; set; }
    
        public virtual Tbl_Sol_IdentificadorOficialGestionTipo Tbl_Sol_IdentificadorOficialGestionTipo { get; set; }
    }
}
