//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Categoria
    {
        public int Id { get; set; }
        public string Categoria_Probosque { get; set; }
        public string Categoria_PinpepOld { get; set; }
        public Nullable<int> Categoria_id { get; set; }
    }
}
