//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gral_VersionesDocumetoISO
    {
        public int Documento_id { get; set; }
        public string Documento { get; set; }
        public string Controlador { get; set; }
        public string Version { get; set; }
        public string Fecha { get; set; }
        public string Codigo { get; set; }
        public Nullable<bool> estado_id { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
    }
}
