//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RSS_Usuario
    {
        public long RSS_id { get; set; }
        public Nullable<long> UsuarioExterno_id { get; set; }
        public string Guid_Solicitud { get; set; }
        public string imagen_url { get; set; }
        public string imagen_Link { get; set; }
        public string Titulo { get; set; }
        public string Cuerpo { get; set; }
        public string Pasos_a_seguir { get; set; }
        public string Link_Pasos_a_seguir { get; set; }
        public string link_A { get; set; }
        public string link_A_descripcion { get; set; }
        public Nullable<bool> link_A_Externo { get; set; }
        public Nullable<bool> link_A_Interno { get; set; }
        public Nullable<bool> link_A_Target_Blank { get; set; }
        public string link_B { get; set; }
        public string link_B_descripcion { get; set; }
        public Nullable<bool> link_B_Externo { get; set; }
        public Nullable<bool> link_B_Interno { get; set; }
        public Nullable<bool> link_B_Target_Blank { get; set; }
        public string link_C { get; set; }
        public string link_C_descripcion { get; set; }
        public Nullable<bool> link_C_Externo { get; set; }
        public Nullable<bool> link_C_Interno { get; set; }
        public Nullable<bool> link_C_Target_Blank { get; set; }
        public string link_D { get; set; }
        public string link_D_descripcion { get; set; }
        public Nullable<bool> link_D_Externo { get; set; }
        public Nullable<bool> link_D_Interno { get; set; }
        public Nullable<bool> link_D_Target_Blank { get; set; }
        public Nullable<bool> InternoLeido { get; set; }
        public Nullable<bool> ExternoLeido { get; set; }
        public Nullable<bool> Msg_ParaInterno { get; set; }
        public Nullable<bool> Msg_ParaExterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public string EtapaSolicitud_GUID_id { get; set; }
        public string ProcesoOrigen { get; set; }
        public Nullable<long> Solicitud_id { get; set; }
    }
}
