//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Seg_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Seg_Usuario()
        {
            this.Tbl_Seg_UsuarioDocumentacion = new HashSet<Tbl_Seg_UsuarioDocumentacion>();
            this.Tbl_Seg_UsuarioRol = new HashSet<Tbl_Seg_UsuarioRol>();
            this.Tbl_Seg_UsuarioSubRegion = new HashSet<Tbl_Seg_UsuarioSubRegion>();
        }
    
        public long Usuario_id { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Usuario { get; set; }
        public string email { get; set; }
        public string whatsapp { get; set; }
        public string PalabraClave { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<System.DateTime> swdateUpdated { get; set; }
        public Nullable<long> swUpdatedby { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> Empleado_id { get; set; }
        public Nullable<bool> NotificacionWhatsapp { get; set; }
        public Nullable<int> DocumentoID_Tipo { get; set; }
        public string No_Documento { get; set; }
        public bool CasilleroElectronico { get; set; }
    
        public virtual Tbl_Gral_DocumentoID_Tipo Tbl_Gral_DocumentoID_Tipo { get; set; }
        public virtual Tbl_Seg_UsuarioEstado Tbl_Seg_UsuarioEstado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Seg_UsuarioDocumentacion> Tbl_Seg_UsuarioDocumentacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Seg_UsuarioRol> Tbl_Seg_UsuarioRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Seg_UsuarioSubRegion> Tbl_Seg_UsuarioSubRegion { get; set; }
    }
}
