//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gest_EtapaSolicitud_Resolucion_Parrafos_Plantilla
    {
        public int ResolucionTipo_id { get; set; }
        public int Categoria_id { get; set; }
        public int Sub_Categoria_id { get; set; }
        public string Parrafo_1 { get; set; }
        public string Parrafo_2 { get; set; }
        public string Parrafo_3 { get; set; }
        public string Parrafo_4 { get; set; }
        public string Parrafo_5 { get; set; }
        public string Parrafo_6 { get; set; }
        public string Parrafo_7 { get; set; }
    
        public virtual Tbl_Gest_EtapaSolicitud_ResolucionTipo Tbl_Gest_EtapaSolicitud_ResolucionTipo { get; set; }
    }
}
