//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gest_EtapaSolicitud_ResolucionTipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Gest_EtapaSolicitud_ResolucionTipo()
        {
            this.Tbl_Gest_EtapaSolicitud_Resolucion_Parrafos_Plantilla = new HashSet<Tbl_Gest_EtapaSolicitud_Resolucion_Parrafos_Plantilla>();
        }
    
        public int ResolucionTipo_id { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Gest_EtapaSolicitud_Resolucion_Parrafos_Plantilla> Tbl_Gest_EtapaSolicitud_Resolucion_Parrafos_Plantilla { get; set; }
    }
}
