//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_Empresa_Entidad_Tipo
    {
        public int EmpresaEntidadTipo_Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Empresa { get; set; }
        public Nullable<bool> Entidad { get; set; }
    }
}
