//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Form_Formulario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Form_Formulario()
        {
            this.Tbl_Form_Formulario_MotivoDenegacion = new HashSet<Tbl_Form_Formulario_MotivoDenegacion>();
            this.Tbl_Form_Formulario_FirmaElectronica_Bitacora = new HashSet<Tbl_Form_Formulario_FirmaElectronica_Bitacora>();
            this.Tbl_Gest_EtapaSolicitud_RespuestaFormulario = new HashSet<Tbl_Gest_EtapaSolicitud_RespuestaFormulario>();
        }
    
        public long Form_Formulario_id { get; set; }
        public Nullable<int> TipoFormulario_id { get; set; }
        public Nullable<bool> Estado_id { get; set; }
        public string ArchivoNombre { get; set; }
        public string Usuario_FirmaElectronica { get; set; }
        public string Password_FirmaElectronica { get; set; }
        public Nullable<int> FirmaElectronica_Estado_id { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Form_Formulario_MotivoDenegacion> Tbl_Form_Formulario_MotivoDenegacion { get; set; }
        public virtual Tbl_Form_FormularioEstado Tbl_Form_FormularioEstado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Form_Formulario_FirmaElectronica_Bitacora> Tbl_Form_Formulario_FirmaElectronica_Bitacora { get; set; }
        public virtual Tbl_Form_Formulario_FirmaElectronica_Estado Tbl_Form_Formulario_FirmaElectronica_Estado { get; set; }
        public virtual Tbl_Gest_Etapa_RespuestaFormulario_Tipo Tbl_Gest_Etapa_RespuestaFormulario_Tipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Gest_EtapaSolicitud_RespuestaFormulario> Tbl_Gest_EtapaSolicitud_RespuestaFormulario { get; set; }
    }
}
