//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gest_Etapa_RespuestaFormulario_Tipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Gest_Etapa_RespuestaFormulario_Tipo()
        {
            this.Tbl_Form_Formulario = new HashSet<Tbl_Form_Formulario>();
            this.Tbl_Gest_Etapa_RespuestaFormulario = new HashSet<Tbl_Gest_Etapa_RespuestaFormulario>();
            this.Tbl_Gest_EtapaSolicitud_RespuestaFormulario = new HashSet<Tbl_Gest_EtapaSolicitud_RespuestaFormulario>();
        }
    
        public int TipoFormulario_id { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> AplicaFirmaDigital { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Form_Formulario> Tbl_Form_Formulario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Gest_Etapa_RespuestaFormulario> Tbl_Gest_Etapa_RespuestaFormulario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Gest_EtapaSolicitud_RespuestaFormulario> Tbl_Gest_EtapaSolicitud_RespuestaFormulario { get; set; }
    }
}
