//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gral_Profesion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Gral_Profesion()
        {
            this.Tbl_RNF_TecnicoProfesional = new HashSet<Tbl_RNF_TecnicoProfesional>();
            this.Tbl_Seg_UsuarioExterno = new HashSet<Tbl_Seg_UsuarioExterno>();
            this.Tbl_Sol_TecnicoProfesional = new HashSet<Tbl_Sol_TecnicoProfesional>();
        }
    
        public int Profesion_id { get; set; }
        public string Descripcion { get; set; }
        public bool Tecnico { get; set; }
        public bool Profesional { get; set; }
        public bool Regente { get; set; }
        public bool ElaboradorDePlanesManejoForestal { get; set; }
        public bool ElaboradorDeEstudiosUsodelSuelo { get; set; }
        public bool CertificadorDeFuentesSemilleras { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<System.DateTime> swdateUpdated { get; set; }
        public Nullable<long> swUpdatedby { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_TecnicoProfesional> Tbl_RNF_TecnicoProfesional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Seg_UsuarioExterno> Tbl_Seg_UsuarioExterno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_TecnicoProfesional> Tbl_Sol_TecnicoProfesional { get; set; }
    }
}
