//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_DocumentosSolicitar
    {
        public int Tipo_Documento_id { get; set; }
        public int Categoria_id { get; set; }
        public int Sub_Categoria_id { get; set; }
        public int Sub_Sub_Categoria_id { get; set; }
    
        public virtual Tbl_Sol_DocumentoTipo Tbl_Sol_DocumentoTipo { get; set; }
        public virtual Tbl_Sol_Solicitud_Categoria Tbl_Sol_Solicitud_Categoria { get; set; }
    }
}
