//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Seg_UsuarioExterno_Dependiente
    {
        public long UsuarioPadre_id { get; set; }
        public long UsuarioHijo_id { get; set; }
        public Nullable<int> Perfil_id { get; set; }
        public Nullable<int> Estado_UsuarioExternoDependiente_id { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
    
        public virtual Tbl_Seg_UsuarioExterno Tbl_Seg_UsuarioExterno { get; set; }
        public virtual Tbl_Seg_UsuarioExterno Tbl_Seg_UsuarioExterno1 { get; set; }
        public virtual Tbl_Seg_UsuarioExterno_Dependiente_Perfil Tbl_Seg_UsuarioExterno_Dependiente_Perfil { get; set; }
    }
}
