//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gral_PerfilesRol
    {
        public int Record_id { get; set; }
        public Nullable<int> Nacional { get; set; }
        public Nullable<int> TecnicoForestal { get; set; }
        public Nullable<int> Regional { get; set; }
        public Nullable<int> SubRegional { get; set; }
        public Nullable<int> Industria { get; set; }
        public Nullable<int> Coodinador { get; set; }
        public Nullable<int> Almacen { get; set; }
        public Nullable<int> DelegadoAdministrativo { get; set; }
        public Nullable<int> JefeIndustria { get; set; }
        public Nullable<int> Secretaria { get; set; }
        public Nullable<int> JuridicoRegional { get; set; }
        public Nullable<int> AsuntosJuridicos { get; set; }
        public Nullable<int> UsuarioExterno { get; set; }
        public Nullable<int> AdministradorRNF { get; set; }
    }
}
