//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Enc_Encuesta_Pregunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Enc_Encuesta_Pregunta()
        {
            this.Tbl_Enc_Encuesta_Respuesta = new HashSet<Tbl_Enc_Encuesta_Respuesta>();
            this.Tbl_EncResp_Encuesta_Pregunta = new HashSet<Tbl_EncResp_Encuesta_Pregunta>();
        }
    
        public int id_encuesta { get; set; }
        public int id_pregunta { get; set; }
        public Nullable<int> id_tipo_respuesta { get; set; }
        public string descripcion { get; set; }
        public bool pregunta_final { get; set; }
        public bool tiene_observacion { get; set; }
        public string titulo_observacion { get; set; }
        public Nullable<int> PreguntaOrigen { get; set; }
        public Nullable<int> RespuestaOrigen { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public bool id_estado { get; set; }
    
        public virtual Tbl_Enc_Encuesta Tbl_Enc_Encuesta { get; set; }
        public virtual Tbl_Enc_Tipo_Respuesta Tbl_Enc_Tipo_Respuesta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Enc_Encuesta_Respuesta> Tbl_Enc_Encuesta_Respuesta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_EncResp_Encuesta_Pregunta> Tbl_EncResp_Encuesta_Pregunta { get; set; }
    }
}
