//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RNF_Rodal_Dasometrico_Especie_Formula
    {
        public string No_Registro { get; set; }
        public string No_RegistroLiteral { get; set; }
        public int No_RegistroCorrelativo { get; set; }
        public long Solicitud_id { get; set; }
        public int RodalDasometricoEspecieFormula_Id { get; set; }
        public string Especie_id { get; set; }
        public string strFormulario { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Tbl_Gral_Especie Tbl_Gral_Especie { get; set; }
        public virtual Tbl_Sol_Rodal_Dasometrico_Especie_Formula_Id Tbl_Sol_Rodal_Dasometrico_Especie_Formula_Id { get; set; }
    }
}
