//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gral_SolicitudConfiguracionCategoria
    {
        public int SolicitudTipo_id { get; set; }
        public Nullable<bool> Usuario { get; set; }
        public Nullable<bool> Propietario { get; set; }
        public Nullable<bool> Representante { get; set; }
        public Nullable<bool> Empresa_entidad { get; set; }
        public Nullable<bool> Finca { get; set; }
        public Nullable<bool> Rodal { get; set; }
        public Nullable<bool> Poligono { get; set; }
        public Nullable<bool> Cultivo { get; set; }
        public Nullable<bool> Dasometricos { get; set; }
        public Nullable<bool> SubirDocumentos { get; set; }
        public Nullable<bool> Motosierra { get; set; }
    }
}
