//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Meta_Mensajes
    {
        public long from { get; set; }
        public long id { get; set; }
        public Nullable<long> timestamp { get; set; }
        public Nullable<System.DateTime> timestamp_dt { get; set; }
        public string type { get; set; }
        public string body { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public string caption { get; set; }
        public string mime_type { get; set; }
        public string sha256 { get; set; }
        public string id_image { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
    }
}
