//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RNF_Registro_Inactivacion_Tipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_RNF_Registro_Inactivacion_Tipo()
        {
            this.Tbl_RNF_Registro = new HashSet<Tbl_RNF_Registro>();
            this.Tbl_Sol_Solicitud = new HashSet<Tbl_Sol_Solicitud>();
        }
    
        public int Categoria_id { get; set; }
        public int TipoInactivacion_id { get; set; }
        public string Descripcion { get; set; }
        public bool UsuarioInterno { get; set; }
        public bool UsuarioExterno { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Registro> Tbl_RNF_Registro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Solicitud> Tbl_Sol_Solicitud { get; set; }
    }
}
