//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_Rodal_Inventario
    {
        public long Solicitud_id { get; set; }
        public long Rodal_id { get; set; }
        public int Arbol_id { get; set; }
        public string Especie_Id { get; set; }
        public Nullable<decimal> GTMX { get; set; }
        public Nullable<decimal> GTMY { get; set; }
        public Nullable<decimal> DAP { get; set; }
        public Nullable<decimal> Altura { get; set; }
        public Nullable<int> InventarioClase_id { get; set; }
        public Nullable<int> EstadoFitosanitario_id { get; set; }
        public Nullable<bool> Estado_id { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
    
        public virtual Tbl_Gral_Especie Tbl_Gral_Especie { get; set; }
        public virtual Tbl_Sol_Rodal_Inventario_Clase Tbl_Sol_Rodal_Inventario_Clase { get; set; }
    }
}
