//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RNF_PropietarioPersonaIndividualHistory
    {
        public string No_Registro { get; set; }
        public string No_RegistroLiteral { get; set; }
        public int No_RegistroCorrelativo { get; set; }
        public long PersonaIndividual_id { get; set; }
        public long Solicitud_id { get; set; }
        public Nullable<int> PuebloPertenencia_id { get; set; }
        public Nullable<int> Sexo_id { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string No_NIT { get; set; }
        public Nullable<int> DocumentoID_Tipo { get; set; }
        public string No_Documento { get; set; }
        public Nullable<int> DepartamentoDPI_id { get; set; }
        public Nullable<int> MunicipioDPI_id { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
        public string Celular { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public Nullable<long> UsuarioExterno_id { get; set; }
        public Nullable<bool> Estado_id { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
    }
}
