//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Seg_OpcionBck
    {
        public int Modulo_id { get; set; }
        public int OpcionTipo_id { get; set; }
        public int Opcion_id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> LastState { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<System.DateTime> swdateUpdated { get; set; }
        public Nullable<long> swUpdatedby { get; set; }
        public string FrmNombre { get; set; }
        public string FrmDescripcion { get; set; }
        public Nullable<int> Orden { get; set; }
        public string Explacion_Funcional { get; set; }
        public string href { get; set; }
    }
}
