//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_EncResp_Encuesta_Pregunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_EncResp_Encuesta_Pregunta()
        {
            this.Tbl_EncResp_Encuesta_Documento = new HashSet<Tbl_EncResp_Encuesta_Documento>();
            this.Tbl_EncResp_Encuesta_PreguntaRespuesta = new HashSet<Tbl_EncResp_Encuesta_PreguntaRespuesta>();
        }
    
        public int id_encuesta { get; set; }
        public long swcreatedby { get; set; }
        public int id_Correlativo { get; set; }
        public int id_pregunta { get; set; }
        public string Respuesta_Observaciones { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
    
        public virtual Tbl_Enc_Encuesta_Pregunta Tbl_Enc_Encuesta_Pregunta { get; set; }
        public virtual Tbl_EncResp_Encuesta Tbl_EncResp_Encuesta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_EncResp_Encuesta_Documento> Tbl_EncResp_Encuesta_Documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_EncResp_Encuesta_PreguntaRespuesta> Tbl_EncResp_Encuesta_PreguntaRespuesta { get; set; }
    }
}
