//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_API_PinpepOld_Finca
    {
        public string Guid_id { get; set; }
        public string FincaMunicipio { get; set; }
        public string FincaDepartamento { get; set; }
        public string FincaUbicacion { get; set; }
        public string FincaLugar { get; set; }
        public string FincaRefX { get; set; }
        public string FincaRefY { get; set; }
        public Nullable<decimal> AreaAprobada { get; set; }
    }
}
