//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gest_EtapaSolicitud_InformeCircunstanciado_Procedimientos
    {
        public long Solicitud_id { get; set; }
        public long Procedimiento_id { get; set; }
        public string Procedimiento { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public string Solicitud_Guid_id { get; set; }
        public string EtapaSolicitud_Guid_id { get; set; }
    
        public virtual Tbl_Gest_EtapaSolicitud_InformeCircunstanciado Tbl_Gest_EtapaSolicitud_InformeCircunstanciado { get; set; }
    }
}
