//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_Finca_FuenteSemillera
    {
        public long Solicitud_id { get; set; }
        public long Finca_id { get; set; }
        public bool PresentaAlgunaPlaga { get; set; }
        public string EspecificarPlaga { get; set; }
        public bool BosqueIntervenido { get; set; }
        public bool AclareoGenetico { get; set; }
        public Nullable<decimal> IngreseDensidadInicial { get; set; }
        public Nullable<decimal> IngreseDensidadFinal { get; set; }
        public Nullable<int> TipoDeEnsayo_id { get; set; }
        public Nullable<int> Procedencia_id { get; set; }
        public string FincaProcedenciaNombre { get; set; }
        public string FincaProcedenciaAldea { get; set; }
        public Nullable<int> FincaProcedenciaDepartamento_id { get; set; }
        public Nullable<int> FincaProcedenciaMunicipio_id { get; set; }
        public Nullable<int> FincaProcedenciaPais_id { get; set; }
        public string RNF_Procedencia { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
        public string RodalesMismaEspecieEspecifique { get; set; }
    
        public virtual Tbl_Gral_FuenteSemillera_Procedencia Tbl_Gral_FuenteSemillera_Procedencia { get; set; }
        public virtual Tbl_Gral_FuenteSemillera_TipoEnsayo Tbl_Gral_FuenteSemillera_TipoEnsayo { get; set; }
    }
}
