//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_Empresa_Entidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Sol_Empresa_Entidad()
        {
            this.Tbl_Sol_Empresa_Entidad_Materia_Prima = new HashSet<Tbl_Sol_Empresa_Entidad_Materia_Prima>();
            this.Tbl_Sol_Empresa_Entidad_Maquinaria_Utilizada = new HashSet<Tbl_Sol_Empresa_Entidad_Maquinaria_Utilizada>();
            this.Tbl_Sol_Empresa_Entidad_Vivero_Forestal = new HashSet<Tbl_Sol_Empresa_Entidad_Vivero_Forestal>();
            this.Tbl_Sol_Empresa_Entidad_Materia_Prima1 = new HashSet<Tbl_Sol_Empresa_Entidad_Materia_Prima>();
            this.Tbl_Sol_Empresa_Entidad_Actividad = new HashSet<Tbl_Sol_Empresa_Entidad_Actividad>();
            this.Tbl_Sol_Empresa_Entidad_TecnicoMateria_Prima = new HashSet<Tbl_Sol_Empresa_Entidad_TecnicoMateria_Prima>();
            this.Tbl_Sol_Empresa_Entidad_TecnicoVivero_Forestal = new HashSet<Tbl_Sol_Empresa_Entidad_TecnicoVivero_Forestal>();
            this.Tbl_Sol_Empresa_Entidad_TecnicoMateria_Prima1 = new HashSet<Tbl_Sol_Empresa_Entidad_TecnicoMateria_Prima>();
            this.Tbl_Sol_Empresa_Entidad_TecnicoMaquinaria_Utilizada = new HashSet<Tbl_Sol_Empresa_Entidad_TecnicoMaquinaria_Utilizada>();
            this.Tbl_Sol_Empresa_Entidad_TecnicoActividad = new HashSet<Tbl_Sol_Empresa_Entidad_TecnicoActividad>();
            this.Tbl_Sol_Motosierra_Marca_Modelo = new HashSet<Tbl_Sol_Motosierra_Marca_Modelo>();
        }
    
        public long Solicitud_id { get; set; }
        public string Nombre { get; set; }
        public string No_NIT { get; set; }
        public string DireccionEmpresa { get; set; }
        public Nullable<int> DepartamentoEmpresaEntidad_id { get; set; }
        public Nullable<int> MunicipioEmpresaEntidad_id { get; set; }
        public string DireccionEmpresaMovil { get; set; }
        public Nullable<int> DepartamentoEmpresaMovilEntidad_id { get; set; }
        public Nullable<int> MunicipioEmpresaEntidadMovil_id { get; set; }
        public string Telefono { get; set; }
        public string email { get; set; }
        public Nullable<decimal> GTMX { get; set; }
        public Nullable<decimal> GTMY { get; set; }
        public Nullable<decimal> GTMX_Tecnico { get; set; }
        public Nullable<decimal> GTMY_Tecnico { get; set; }
        public Nullable<long> UsuarioExterno_id { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
        public Nullable<decimal> CapacidadInstalada { get; set; }
        public string Aldea { get; set; }
        public string Objeto_Empresa { get; set; }
        public Nullable<int> Tipo_Industria_id { get; set; }
        public string RNF_Inscripcion_Vinculada { get; set; }
    
        public virtual Tbl_Gral_Departamento Tbl_Gral_Departamento { get; set; }
        public virtual Tbl_Gral_Departamento Tbl_Gral_Departamento1 { get; set; }
        public virtual Tbl_Gral_Municipio Tbl_Gral_Municipio { get; set; }
        public virtual Tbl_Gral_Municipio Tbl_Gral_Municipio1 { get; set; }
        public virtual Tbl_Gral_Tipo_Industria Tbl_Gral_Tipo_Industria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Empresa_Entidad_Materia_Prima> Tbl_Sol_Empresa_Entidad_Materia_Prima { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Empresa_Entidad_Maquinaria_Utilizada> Tbl_Sol_Empresa_Entidad_Maquinaria_Utilizada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Empresa_Entidad_Vivero_Forestal> Tbl_Sol_Empresa_Entidad_Vivero_Forestal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Empresa_Entidad_Materia_Prima> Tbl_Sol_Empresa_Entidad_Materia_Prima1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Empresa_Entidad_Actividad> Tbl_Sol_Empresa_Entidad_Actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Empresa_Entidad_TecnicoMateria_Prima> Tbl_Sol_Empresa_Entidad_TecnicoMateria_Prima { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Empresa_Entidad_TecnicoVivero_Forestal> Tbl_Sol_Empresa_Entidad_TecnicoVivero_Forestal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Empresa_Entidad_TecnicoMateria_Prima> Tbl_Sol_Empresa_Entidad_TecnicoMateria_Prima1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Empresa_Entidad_TecnicoMaquinaria_Utilizada> Tbl_Sol_Empresa_Entidad_TecnicoMaquinaria_Utilizada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Empresa_Entidad_TecnicoActividad> Tbl_Sol_Empresa_Entidad_TecnicoActividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Motosierra_Marca_Modelo> Tbl_Sol_Motosierra_Marca_Modelo { get; set; }
        public virtual Tbl_Sol_Solicitud Tbl_Sol_Solicitud { get; set; }
        public virtual Tbl_Sol_Empresa_Entidad_Tipo_Registro Tbl_Sol_Empresa_Entidad_Tipo_Registro { get; set; }
    }
}
