//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RNF_Empresa_Entidad_Maquinaria_UtilizadaHistory
    {
        public string No_Registro { get; set; }
        public string No_RegistroLiteral { get; set; }
        public int No_RegistroCorrelativo { get; set; }
        public long Solicitud_id { get; set; }
        public int Maquinaria_Utilizada_id { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
    }
}
