//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_Solicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Sol_Solicitud()
        {
            this.Tbl_Gest_EtapaSolicitud = new HashSet<Tbl_Gest_EtapaSolicitud>();
            this.Tbl_Sol_ArrendatarioPersonaIndividual = new HashSet<Tbl_Sol_ArrendatarioPersonaIndividual>();
            this.Tbl_Sol_ArrendatarioPersonaJuridica = new HashSet<Tbl_Sol_ArrendatarioPersonaJuridica>();
            this.Tbl_Sol_DocumentoSubido = new HashSet<Tbl_Sol_DocumentoSubido>();
            this.Tbl_Sol_Finca = new HashSet<Tbl_Sol_Finca>();
            this.Tbl_Sol_Motosierra = new HashSet<Tbl_Sol_Motosierra>();
            this.Tbl_Sol_PropietarioPersonaIndividual = new HashSet<Tbl_Sol_PropietarioPersonaIndividual>();
            this.Tbl_Sol_PropietarioPersonaJuridica = new HashSet<Tbl_Sol_PropietarioPersonaJuridica>();
            this.Tbl_Sol_RepresentanteLegal = new HashSet<Tbl_Sol_RepresentanteLegal>();
            this.Tbl_Sol_Rodal_Dasometrico_Especie_Formula = new HashSet<Tbl_Sol_Rodal_Dasometrico_Especie_Formula>();
        }
    
        public long Solicitud_id { get; set; }
        public Nullable<int> Region_id { get; set; }
        public Nullable<int> SubRegion_id { get; set; }
        public Nullable<int> Categoria_id { get; set; }
        public Nullable<int> Sub_Categoria_id { get; set; }
        public Nullable<int> Sub_Sub_Categoria_id { get; set; }
        public string Guid_id { get; set; }
        public Nullable<int> Estado_id { get; set; }
        public Nullable<decimal> AreaTotalFincas { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
        public string Solicitud_NumeroTemporal { get; set; }
        public string Solicitud_NumeroExpediente { get; set; }
        public string FacturaSerie { get; set; }
        public string FacturaNumero { get; set; }
        public Nullable<int> CantidadFolios { get; set; }
        public Nullable<System.DateTime> FechaRecepcionExpedienteFisico { get; set; }
        public Nullable<long> RecepcionExpedienteFisicoby { get; set; }
        public Nullable<long> SecretariaAsignada_id { get; set; }
        public Nullable<long> TecnicoAsignado_id { get; set; }
        public Nullable<long> JuridicoAsignado_id { get; set; }
        public string JuridicoAsignadoNombramiento { get; set; }
        public Nullable<System.DateTime> JuridicoAsignadoFecha { get; set; }
        public Nullable<System.DateTime> TecnicoAsignadoFecha { get; set; }
        public Nullable<long> JuridicoAsignadoPorSubRegional_id { get; set; }
        public Nullable<long> TecnicoAsignadoPorSubRegional_id { get; set; }
        public Nullable<int> PonderacionEvaluacionTecnica_id { get; set; }
        public Nullable<int> PonderacionEvaluacionTecnicaFormulario_id { get; set; }
        public Nullable<int> PonderacionEvaluacionTecnicaDeArea_id { get; set; }
        public Nullable<int> PonderacionEvaluacionTecnicaDasometrica_id { get; set; }
        public Nullable<int> PonderacionEvaluacionJuridica_id { get; set; }
        public Nullable<int> TipoGestion_id { get; set; }
        public Nullable<bool> PermitirCambioDePropietarioRepresentante { get; set; }
        public Nullable<bool> PermitirCambioFincaRodalesDasometricos { get; set; }
        public Nullable<bool> PermitirSubirDocumentos { get; set; }
        public string No_Registro { get; set; }
        public string No_RegistroLiteral { get; set; }
        public Nullable<int> No_RegistroCorrelativo { get; set; }
        public string ResolucionInscripcion { get; set; }
        public Nullable<System.DateTime> ResolucionInscripcionFecha { get; set; }
        public Nullable<System.DateTime> InscripcionFecha { get; set; }
        public decimal SolicitudTipo_id { get; set; }
        public Nullable<bool> EnmiendasRecibidas { get; set; }
        public Nullable<int> TipoInactivacion_id { get; set; }
        public string Descripcion_Inactivacion { get; set; }
        public Nullable<bool> PermitirCambiosEnDatosMotosierra { get; set; }
        public Nullable<int> DepartamentoSolicitud_id { get; set; }
        public Nullable<int> MunicipioSolicitud_id { get; set; }
        public Nullable<bool> PermitirCambioEnDatosTecnicoProfesional { get; set; }
        public string DPI_Titular { get; set; }
        public string DocumentoVinculado { get; set; }
        public bool Procedencia_Probosque { get; set; }
        public bool Procedencia_PinpepOld { get; set; }
        public bool Procedencia_PinpepNew { get; set; }
        public bool Procedencia_secorf { get; set; }
        public string Procedencia_Expediente { get; set; }
        public string Procedencia_POA { get; set; }
        public string Procedencia_Licencia { get; set; }
        public string Procedencia_Modalidad { get; set; }
        public string Procedencia_Fase { get; set; }
        public string Procedencia_NombreSolicitante { get; set; }
        public string Procedencia_TipoProyecto { get; set; }
        public string Procedencia_InformeTecnico { get; set; }
        public Nullable<System.DateTime> Procedencia_FechaInicioPeriodo { get; set; }
        public Nullable<System.DateTime> Procedencia_FechaFinPeriodo { get; set; }
        public Nullable<System.DateTime> Fecha_De_Inscripcion_RNF { get; set; }
        public string Resolucion_De_Inscripcion_RNF { get; set; }
        public Nullable<System.DateTime> Fecha_De_ResolucionInscripcion_RNF { get; set; }
        public Nullable<System.DateTime> FechaResolucionSolicitud { get; set; }
        public string ResolucionSolicitud { get; set; }
        public Nullable<int> InactivacionTecnicoTipo_id { get; set; }
        public string Descripcion_InactivacionTecnico { get; set; }
        public Nullable<long> Bitacora_id { get; set; }
        public string Notificacion_Direccion { get; set; }
        public int Notificacion_Municipio_id { get; set; }
        public int Notificacion_Departamento_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Gest_EtapaSolicitud> Tbl_Gest_EtapaSolicitud { get; set; }
        public virtual Tbl_Gral_Departamento Tbl_Gral_Departamento { get; set; }
        public virtual Tbl_Gral_EvaluacionPonderacion Tbl_Gral_EvaluacionPonderacion { get; set; }
        public virtual Tbl_Gral_EvaluacionPonderacion Tbl_Gral_EvaluacionPonderacion1 { get; set; }
        public virtual Tbl_Gral_EvaluacionPonderacion Tbl_Gral_EvaluacionPonderacion2 { get; set; }
        public virtual Tbl_Gral_Municipio Tbl_Gral_Municipio { get; set; }
        public virtual Tbl_Gral_Region Tbl_Gral_Region { get; set; }
        public virtual Tbl_Gral_SolicitudConfiguracionTipo Tbl_Gral_SolicitudConfiguracionTipo { get; set; }
        public virtual Tbl_Gral_SubRegion Tbl_Gral_SubRegion { get; set; }
        public virtual Tbl_RNF_Registro_Inactivacion_Tipo Tbl_RNF_Registro_Inactivacion_Tipo { get; set; }
        public virtual Tbl_RNF_Registro_InactivacionTecnico_Tipo Tbl_RNF_Registro_InactivacionTecnico_Tipo { get; set; }
        public virtual Tbl_Seg_UsuarioExterno Tbl_Seg_UsuarioExterno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_ArrendatarioPersonaIndividual> Tbl_Sol_ArrendatarioPersonaIndividual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_ArrendatarioPersonaJuridica> Tbl_Sol_ArrendatarioPersonaJuridica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_DocumentoSubido> Tbl_Sol_DocumentoSubido { get; set; }
        public virtual Tbl_Sol_Empresa_Entidad Tbl_Sol_Empresa_Entidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Finca> Tbl_Sol_Finca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Motosierra> Tbl_Sol_Motosierra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_PropietarioPersonaIndividual> Tbl_Sol_PropietarioPersonaIndividual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_PropietarioPersonaJuridica> Tbl_Sol_PropietarioPersonaJuridica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_RepresentanteLegal> Tbl_Sol_RepresentanteLegal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Rodal_Dasometrico_Especie_Formula> Tbl_Sol_Rodal_Dasometrico_Especie_Formula { get; set; }
        public virtual Tbl_Sol_Solicitud_Categoria Tbl_Sol_Solicitud_Categoria { get; set; }
        public virtual Tbl_Sol_Solicitud_Estado Tbl_Sol_Solicitud_Estado { get; set; }
        public virtual Tbl_Sol_Solicitud_Sub_Categoria Tbl_Sol_Solicitud_Sub_Categoria { get; set; }
        public virtual Tbl_Sol_TecnicoProfesional Tbl_Sol_TecnicoProfesional { get; set; }
    }
}
