//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_EncResp_Encuesta_PreguntaRespuesta
    {
        public int id_encuesta { get; set; }
        public long swcreatedby { get; set; }
        public int id_Correlativo { get; set; }
        public int id_pregunta { get; set; }
        public int id_respuesta { get; set; }
        public string Respuesta_Observaciones { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
    
        public virtual Tbl_Enc_Encuesta_Respuesta Tbl_Enc_Encuesta_Respuesta { get; set; }
        public virtual Tbl_EncResp_Encuesta_Pregunta Tbl_EncResp_Encuesta_Pregunta { get; set; }
    }
}
