//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RNF_Rodal_Descuento
    {
        public string No_Registro { get; set; }
        public string No_RegistroLiteral { get; set; }
        public int No_RegistroCorrelativo { get; set; }
        public long Solicitud_id { get; set; }
        public long Finca_id { get; set; }
        public int Tipo_de_Area { get; set; }
        public long Rodal_Id { get; set; }
        public long Rodal_Descuento_Id { get; set; }
        public Nullable<decimal> AreaTotal { get; set; }
        public Nullable<decimal> AreaTotalCalculadaSistema { get; set; }
        public Nullable<decimal> Longitud_Total { get; set; }
        public Nullable<decimal> GTMX { get; set; }
        public Nullable<decimal> GTMY { get; set; }
        public Nullable<decimal> GTMX_Min { get; set; }
        public Nullable<decimal> GTMX_Max { get; set; }
        public Nullable<decimal> GTMY_Min { get; set; }
        public Nullable<decimal> GTMY_Max { get; set; }
        public Nullable<int> CultivoSAF_Id { get; set; }
        public bool Colecta_De_Datos_X_Censo { get; set; }
        public bool Colecta_De_Datos_X_Muestreo { get; set; }
        public Nullable<int> Colecta_De_Datos_X_Muestreo_No_Parcelas { get; set; }
        public Nullable<decimal> Colecta_De_Datos_X_Muestreo_Area_Parcelas { get; set; }
        public bool Area_SIGAP { get; set; }
        public Nullable<int> CategoriaSIGAP_Id { get; set; }
        public bool Procedencia_Pinfor { get; set; }
        public bool Procedencia_Pinpep { get; set; }
        public bool Procedencia_Probosque { get; set; }
        public string Procedencia_No_Expediente { get; set; }
        public Nullable<int> Procedencia_AnioInicial { get; set; }
        public Nullable<int> Procedencia_AnioFinal { get; set; }
        public Nullable<long> AreaRegion_Id { get; set; }
        public Nullable<long> AreaProtegida_Id { get; set; }
        public string Inconvenientes { get; set; }
        public Nullable<bool> InconvenientesBloqueantes { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
    }
}
