//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gral_Secorf_TipoRegistro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Gral_Secorf_TipoRegistro()
        {
            this.Tbl_RNF_Rodal = new HashSet<Tbl_RNF_Rodal>();
            this.Tbl_Sol_Rodal = new HashSet<Tbl_Sol_Rodal>();
        }
    
        public int Secorf_TipoRegistro_id { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Rodal> Tbl_RNF_Rodal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Rodal> Tbl_Sol_Rodal { get; set; }
    }
}
