//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Form_Formulario_FirmaElectronica_Bitacora
    {
        public long Form_Formulario_id { get; set; }
        public string Firmante { get; set; }
        public int FirmaElectronica_Estado_id { get; set; }
        public string Resultado { get; set; }
        public System.DateTime swdatecreated { get; set; }
        public string Guid_id { get; set; }
        public string GuidEtapa_id { get; set; }
    
        public virtual Tbl_Form_Formulario Tbl_Form_Formulario { get; set; }
        public virtual Tbl_Form_Formulario_FirmaElectronica_Estado Tbl_Form_Formulario_FirmaElectronica_Estado { get; set; }
    }
}
