//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RNF_Finca_Secorf_EspeciesForestalesHistory
    {
        public string No_Registro { get; set; }
        public string No_RegistroLiteral { get; set; }
        public int No_RegistroCorrelativo { get; set; }
        public long Solicitud_id { get; set; }
        public long Finca_id { get; set; }
        public int Tipo_de_Area { get; set; }
        public long Rodal_id { get; set; }
        public int Correlativo_id { get; set; }
        public Nullable<decimal> Area_ha { get; set; }
        public string Especie_id { get; set; }
        public Nullable<decimal> DAP { get; set; }
        public Nullable<decimal> Altura { get; set; }
        public Nullable<decimal> Densidad_ha { get; set; }
        public Nullable<decimal> Volumen { get; set; }
        public Nullable<int> Anio_Establecimiento { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
    }
}
