//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gest_EtapaSolicitud_OficioJuridico_Enmienda
    {
        public long Solicitud_id { get; set; }
        public int Etapa_id { get; set; }
        public decimal EtapaRuta_id { get; set; }
        public int CorrelativoEtapa_id { get; set; }
        public int Enmienda_id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public string EtapaSolicitud_GUID_id { get; set; }
        public string Solicitud_Guid_id { get; set; }
        public Nullable<long> swcriticadoby { get; set; }
        public Nullable<bool> swcriticadobyinterno { get; set; }
        public Nullable<System.DateTime> swdatecriticadoby { get; set; }
        public Nullable<bool> Estado_id { get; set; }
        public string Objecion { get; set; }
    }
}
