//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Seg_Privilegio
    {
        public int Modulo_id { get; set; }
        public int OpcionTipo_id { get; set; }
        public int Opcion_id { get; set; }
        public int Rol_id { get; set; }
        public bool Visualizar { get; set; }
        public bool Adicionar { get; set; }
        public bool Editar { get; set; }
        public bool Imprimir { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<System.DateTime> swdateUpdated { get; set; }
        public Nullable<long> swUpdatedby { get; set; }
    
        public virtual Tbl_Seg_Opcion Tbl_Seg_Opcion { get; set; }
        public virtual Tbl_Seg_Rol Tbl_Seg_Rol { get; set; }
    }
}
