//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_API_PinpepOld_Expediente
    {
        public string Guid_id { get; set; }
        public Nullable<long> ProyectoId { get; set; }
        public string Expediente { get; set; }
        public string Modalidad { get; set; }
        public string Region { get; set; }
        public string SubRegion { get; set; }
        public string UltimaFaseCertificada { get; set; }
        public Nullable<decimal> UltimaAreaCertificada { get; set; }
        public Nullable<bool> Migrado { get; set; }
        public Nullable<long> Solicitud_id { get; set; }
        public string DPI_Titular { get; set; }
    }
}
