//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RNF_Finca
    {
        public string No_Registro { get; set; }
        public string No_RegistroLiteral { get; set; }
        public int No_RegistroCorrelativo { get; set; }
        public long Solicitud_id { get; set; }
        public long Finca_Id { get; set; }
        public string NombreFinca { get; set; }
        public Nullable<int> ConstanciaDePropiedad_id { get; set; }
        public string ConstanciaPropiedadDescripcion { get; set; }
        public string RegNumero { get; set; }
        public string RegFolio { get; set; }
        public string RegLibro { get; set; }
        public Nullable<int> RegDepartamento_id { get; set; }
        public string ActaNotarial_Notario { get; set; }
        public string ActaNotarialConCertificacion_NombreDeCertificador { get; set; }
        public string ActaNotarialDeEscrituraPublica_Numero { get; set; }
        public Nullable<System.DateTime> ActaNotarialDeEscrituraPublica_Fecha { get; set; }
        public Nullable<int> DepartamentoFinca_Id { get; set; }
        public Nullable<int> MunicipioFinca_Id { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<decimal> AreaTotal { get; set; }
        public Nullable<decimal> AreaARegistrar { get; set; }
        public Nullable<int> ObjetivoDeLaPlantacion { get; set; }
        public Nullable<decimal> GTMX { get; set; }
        public Nullable<decimal> GTMY { get; set; }
        public bool OtrosRegistrosRNF { get; set; }
        public bool NoOtrosRegistrosRNF { get; set; }
        public string Registros { get; set; }
        public string NombreAreaSIGAP { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
        public bool Area_SIGAP { get; set; }
        public bool Reforestacion_CONAP { get; set; }
        public Nullable<int> CategoriaSIGAP_Id { get; set; }
    
        public virtual Tbl_Gral_Departamento Tbl_Gral_Departamento { get; set; }
        public virtual Tbl_Gral_DepartamentoRegistro Tbl_Gral_DepartamentoRegistro { get; set; }
        public virtual Tbl_Gral_Municipio Tbl_Gral_Municipio { get; set; }
        public virtual Tbl_Sol_FincaConstanciaDePropiedad Tbl_Sol_FincaConstanciaDePropiedad { get; set; }
        public virtual Tbl_Sol_FincaObjetivoDeLaPlantacion Tbl_Sol_FincaObjetivoDeLaPlantacion { get; set; }
    }
}
