//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gral_Materia_Prima
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Gral_Materia_Prima()
        {
            this.Tbl_RNF_Empresa_Entidad_Materia_Prima = new HashSet<Tbl_RNF_Empresa_Entidad_Materia_Prima>();
            this.Tbl_RNF_Empresa_Entidad_Materia_Prima1 = new HashSet<Tbl_RNF_Empresa_Entidad_Materia_Prima>();
            this.Tbl_Sol_Empresa_Entidad_Materia_Prima = new HashSet<Tbl_Sol_Empresa_Entidad_Materia_Prima>();
            this.Tbl_Sol_Empresa_Entidad_TecnicoMateria_Prima = new HashSet<Tbl_Sol_Empresa_Entidad_TecnicoMateria_Prima>();
            this.Tbl_Sol_Empresa_Entidad_TecnicoMateria_Prima1 = new HashSet<Tbl_Sol_Empresa_Entidad_TecnicoMateria_Prima>();
            this.Tbl_Sol_Empresa_Entidad_Materia_Prima1 = new HashSet<Tbl_Sol_Empresa_Entidad_Materia_Prima>();
        }
    
        public int Materia_Prima_Id { get; set; }
        public string Nombre_Tecnico { get; set; }
        public string Nombres_Comunes { get; set; }
        public bool Industria_Forestal { get; set; }
        public bool Deposito_Forestal { get; set; }
        public bool Centro_Acopio { get; set; }
        public bool Viveros_Forestales { get; set; }
        public bool Exporta_Importa_Producto_Forestal { get; set; }
        public bool Producto_Forestal_No_Maderable { get; set; }
        public bool Repobladoras_Forestales { get; set; }
        public bool Consultora_Forestal { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
        public bool Estado_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Empresa_Entidad_Materia_Prima> Tbl_RNF_Empresa_Entidad_Materia_Prima { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Empresa_Entidad_Materia_Prima> Tbl_RNF_Empresa_Entidad_Materia_Prima1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Empresa_Entidad_Materia_Prima> Tbl_Sol_Empresa_Entidad_Materia_Prima { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Empresa_Entidad_TecnicoMateria_Prima> Tbl_Sol_Empresa_Entidad_TecnicoMateria_Prima { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Empresa_Entidad_TecnicoMateria_Prima> Tbl_Sol_Empresa_Entidad_TecnicoMateria_Prima1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Empresa_Entidad_Materia_Prima> Tbl_Sol_Empresa_Entidad_Materia_Prima1 { get; set; }
    }
}
