//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RNF_RegistroHistory
    {
        public string No_Registro { get; set; }
        public string No_RegistroLiteral { get; set; }
        public int No_RegistroCorrelativo { get; set; }
        public string Expediente { get; set; }
        public Nullable<int> Region_id { get; set; }
        public Nullable<int> SubRegion_id { get; set; }
        public Nullable<int> Categoria_id { get; set; }
        public Nullable<int> Sub_Categoria_id { get; set; }
        public Nullable<int> Sub_Sub_Categoria_id { get; set; }
        public string Guid_id { get; set; }
        public Nullable<int> Estado_id { get; set; }
        public Nullable<System.DateTime> Fecha_De_Vencimiento { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
        public Nullable<int> Old_RegistroId_Identity { get; set; }
        public Nullable<int> Old_TipoRegistroId { get; set; }
        public Nullable<int> Old_RegistradorId { get; set; }
        public Nullable<long> UsuarioExterno_id { get; set; }
        public long Solicitud_id { get; set; }
        public string GuidSolicitud_id { get; set; }
        public string DPI_Titular { get; set; }
        public Nullable<decimal> AreaTotalFincas { get; set; }
        public Nullable<int> TipoInactivacion_id { get; set; }
        public string Descripcion_Inactivacion { get; set; }
        public string ResolucionInscripcion { get; set; }
        public Nullable<System.DateTime> ResolucionInscripcionFecha { get; set; }
        public string ResolucionUltimaActualizacion { get; set; }
        public Nullable<System.DateTime> ResolucionUltimaActualizacionFecha { get; set; }
        public string ResolucionUltimaInactivacion { get; set; }
        public Nullable<System.DateTime> ResolucionUltimaInactivacionFecha { get; set; }
        public string ConstanciaFirmada { get; set; }
        public Nullable<decimal> SolicitudTipo_id { get; set; }
        public Nullable<System.DateTime> FechaModificacionDisponible { get; set; }
        public bool Procedencia_Probosque { get; set; }
        public bool Procedencia_PinpepOld { get; set; }
        public bool Procedencia_PinpepNew { get; set; }
        public bool Procedencia_secorf { get; set; }
        public string Procedencia_Expediente { get; set; }
        public string Procedencia_POA { get; set; }
        public string Procedencia_Licencia { get; set; }
        public string Procedencia_Modalidad { get; set; }
        public string Procedencia_Fase { get; set; }
        public string Procedencia_NombreSolicitante { get; set; }
        public string Procedencia_TipoProyecto { get; set; }
        public string Procedencia_InformeTecnico { get; set; }
        public Nullable<System.DateTime> Procedencia_FechaInicioPeriodo { get; set; }
        public Nullable<System.DateTime> Procedencia_FechaFinPeriodo { get; set; }
        public Nullable<System.DateTime> Fecha_Inscripcion { get; set; }
        public Nullable<System.DateTime> Fecha_Actualizacion { get; set; }
        public Nullable<System.DateTime> Fecha_Inactivacion { get; set; }
        public Nullable<int> InactivacionTecnicoTipo_id { get; set; }
        public string Descripcion_InactivacionTecnico { get; set; }
        public Nullable<long> Bitacora_id { get; set; }
        public string Notificacion_Direccion { get; set; }
        public int Notificacion_Municipio_id { get; set; }
        public int Notificacion_Departamento_id { get; set; }
    
        public virtual Tbl_Gral_SolicitudConfiguracionTipo Tbl_Gral_SolicitudConfiguracionTipo { get; set; }
    }
}
