//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gral_Especie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Gral_Especie()
        {
            this.Tbl_RNF_Empresa_Entidad_Vivero_Forestal = new HashSet<Tbl_RNF_Empresa_Entidad_Vivero_Forestal>();
            this.Tbl_Sol_Empresa_Entidad_Vivero_Forestal = new HashSet<Tbl_Sol_Empresa_Entidad_Vivero_Forestal>();
            this.Tbl_Sol_Empresa_Entidad_TecnicoVivero_Forestal = new HashSet<Tbl_Sol_Empresa_Entidad_TecnicoVivero_Forestal>();
            this.Tbl_RNF_Rodal_Dasometrico_Especie_Formula = new HashSet<Tbl_RNF_Rodal_Dasometrico_Especie_Formula>();
            this.Tbl_RNF_Rodal_Dasometrico = new HashSet<Tbl_RNF_Rodal_Dasometrico>();
            this.Tbl_RNF_Rodal_Inventario = new HashSet<Tbl_RNF_Rodal_Inventario>();
            this.Tbl_Sol_Rodal_Dasometrico_Especie_Formula = new HashSet<Tbl_Sol_Rodal_Dasometrico_Especie_Formula>();
            this.Tbl_Sol_Rodal_Dasometrico = new HashSet<Tbl_Sol_Rodal_Dasometrico>();
            this.Tbl_Sol_Rodal_Inventario = new HashSet<Tbl_Sol_Rodal_Inventario>();
        }
    
        public string Especie_Id { get; set; }
        public string NombreCientifico { get; set; }
        public string NombresComunes { get; set; }
        public string Autores { get; set; }
        public string Sinonimos { get; set; }
        public string Familia { get; set; }
        public Nullable<int> Id { get; set; }
        public bool ArbolFrutal { get; set; }
        public bool Conifera { get; set; }
        public bool Latifoliada { get; set; }
        public bool Estado_id { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Empresa_Entidad_Vivero_Forestal> Tbl_RNF_Empresa_Entidad_Vivero_Forestal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Empresa_Entidad_Vivero_Forestal> Tbl_Sol_Empresa_Entidad_Vivero_Forestal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Empresa_Entidad_TecnicoVivero_Forestal> Tbl_Sol_Empresa_Entidad_TecnicoVivero_Forestal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Rodal_Dasometrico_Especie_Formula> Tbl_RNF_Rodal_Dasometrico_Especie_Formula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Rodal_Dasometrico> Tbl_RNF_Rodal_Dasometrico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Rodal_Inventario> Tbl_RNF_Rodal_Inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Rodal_Dasometrico_Especie_Formula> Tbl_Sol_Rodal_Dasometrico_Especie_Formula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Rodal_Dasometrico> Tbl_Sol_Rodal_Dasometrico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Rodal_Inventario> Tbl_Sol_Rodal_Inventario { get; set; }
    }
}
