//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_API_PinpepOld_PropietariosGrupal
    {
        public string Guid_id { get; set; }
        public long Id_PropietarioGrupal { get; set; }
        public string NoDPI { get; set; }
        public string NombreCompleto { get; set; }
    }
}
