//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_Rodal_Dasometrico_VolumenCenso
    {
        public long Solicitud_id { get; set; }
        public long Finca_id { get; set; }
        public long Rodal_id { get; set; }
        public int Tipo_de_Area { get; set; }
        public long Dasometrico_id { get; set; }
        public Nullable<decimal> AreaBasal_MetroCuadrado { get; set; }
        public Nullable<decimal> AreaBasal_Hectarea { get; set; }
        public Nullable<decimal> Volumen_MetrosCubicos { get; set; }
        public Nullable<decimal> Volumen_ha { get; set; }
    }
}
