//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_DocumentosSolicitarAuxiliar
    {
        public long Solicitud_id { get; set; }
        public int Tipo_Documento_id { get; set; }
        public Nullable<int> Parametro_Id { get; set; }
        public string Descripcion { get; set; }
        public string Realizado { get; set; }
        public string No_Realizado { get; set; }
        public Nullable<bool> Bloqueante { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
    }
}
