//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_Rodal_Tipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Sol_Rodal_Tipo()
        {
            this.Tbl_RNF_Finca_Secorf_EspeciesForestales = new HashSet<Tbl_RNF_Finca_Secorf_EspeciesForestales>();
            this.Tbl_RNF_Rodal = new HashSet<Tbl_RNF_Rodal>();
            this.Tbl_RNF_Rodal_Cultivo = new HashSet<Tbl_RNF_Rodal_Cultivo>();
            this.Tbl_RNF_Rodal_Dasometrico = new HashSet<Tbl_RNF_Rodal_Dasometrico>();
            this.Tbl_Sol_Finca_Secorf_EspeciesForestales = new HashSet<Tbl_Sol_Finca_Secorf_EspeciesForestales>();
            this.Tbl_Sol_Rodal = new HashSet<Tbl_Sol_Rodal>();
            this.Tbl_Sol_Rodal_Cultivo = new HashSet<Tbl_Sol_Rodal_Cultivo>();
            this.Tbl_Sol_Rodal_CultivoTecnico = new HashSet<Tbl_Sol_Rodal_CultivoTecnico>();
            this.Tbl_Sol_Rodal_Dasometrico = new HashSet<Tbl_Sol_Rodal_Dasometrico>();
        }
    
        public int Tipo_de_Area { get; set; }
        public string Descripcion { get; set; }
        public string Abreviatura { get; set; }
        public string Metrica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Finca_Secorf_EspeciesForestales> Tbl_RNF_Finca_Secorf_EspeciesForestales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Rodal> Tbl_RNF_Rodal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Rodal_Cultivo> Tbl_RNF_Rodal_Cultivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RNF_Rodal_Dasometrico> Tbl_RNF_Rodal_Dasometrico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Finca_Secorf_EspeciesForestales> Tbl_Sol_Finca_Secorf_EspeciesForestales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Rodal> Tbl_Sol_Rodal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Rodal_Cultivo> Tbl_Sol_Rodal_Cultivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Rodal_CultivoTecnico> Tbl_Sol_Rodal_CultivoTecnico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Rodal_Dasometrico> Tbl_Sol_Rodal_Dasometrico { get; set; }
    }
}
