//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_Empresa_Entidad_TecnicoMaquinaria_Utilizada
    {
        public long Solicitud_id { get; set; }
        public int Maquinaria_Utilizada_id { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
    
        public virtual Tbl_Gral_Maquinaria_Utilizada Tbl_Gral_Maquinaria_Utilizada { get; set; }
        public virtual Tbl_Gral_Maquinaria_Utilizada Tbl_Gral_Maquinaria_Utilizada1 { get; set; }
        public virtual Tbl_Sol_Empresa_Entidad Tbl_Sol_Empresa_Entidad { get; set; }
    }
}
