//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_DocumentoSubido
    {
        public long Solicitud_id { get; set; }
        public int Documento_id { get; set; }
        public Nullable<long> Finca_id { get; set; }
        public Nullable<long> Representante_id { get; set; }
        public Nullable<long> Propietario_id { get; set; }
        public Nullable<int> Etapa_id { get; set; }
        public Nullable<int> Correlativo_id { get; set; }
        public Nullable<long> Motosierra_id { get; set; }
        public int Tipo_Documento_id { get; set; }
        public string FileName { get; set; }
        public string FileRef { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<bool> DocumentoVerificado { get; set; }
        public Nullable<bool> DocumentoRecibido { get; set; }
        public Nullable<bool> DocumentoVerificadoNotario { get; set; }
    
        public virtual Tbl_Sol_Solicitud Tbl_Sol_Solicitud { get; set; }
        public virtual Tbl_Sol_DocumentoTipo Tbl_Sol_DocumentoTipo { get; set; }
    }
}
