//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_Rodal_Dasometrico_ValidacionesDiametrica
    {
        public long Solicitud_id { get; set; }
        public long Finca_id { get; set; }
        public long Rodal_id { get; set; }
        public int No_Parcela { get; set; }
        public int Tipo_de_Area { get; set; }
        public string ClaseDiametrica { get; set; }
        public Nullable<decimal> Cantidad_Arboles { get; set; }
        public Nullable<decimal> Densidad_ha { get; set; }
        public Nullable<decimal> AlturaPromedio { get; set; }
        public Nullable<decimal> AreaBasal_ha { get; set; }
        public Nullable<decimal> Volumen_ha { get; set; }
        public Nullable<decimal> Volumen_Rodal { get; set; }
        public string Especie_id { get; set; }
        public string EstimacionPorMedioDe { get; set; }
        public string Anio_Plantacion { get; set; }
        public Nullable<decimal> Volumen_X_Linea { get; set; }
        public Nullable<decimal> Area_Basal_MetroCuadrado { get; set; }
        public int Clase { get; set; }
    }
}
