//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_ArrendatarioPersonaIndividual
    {
        public long PersonaIndividual_id { get; set; }
        public long Solicitud_id { get; set; }
        public Nullable<int> PuebloPertenencia_id { get; set; }
        public Nullable<int> Sexo_id { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string No_NIT { get; set; }
        public Nullable<int> DocumentoID_Tipo { get; set; }
        public string No_Documento { get; set; }
        public Nullable<int> DepartamentoDPI_id { get; set; }
        public Nullable<int> MunicipioDPI_id { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
        public string Celular { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public Nullable<long> UsuarioExterno_id { get; set; }
        public Nullable<bool> Estado_id { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
    
        public virtual Tbl_Gral_Departamento Tbl_Gral_Departamento { get; set; }
        public virtual Tbl_Gral_DocumentoID_Tipo Tbl_Gral_DocumentoID_Tipo { get; set; }
        public virtual Tbl_Gral_Municipio Tbl_Gral_Municipio { get; set; }
        public virtual Tbl_Gral_PuebloPertenencia Tbl_Gral_PuebloPertenencia { get; set; }
        public virtual Tbl_Gral_Sexo Tbl_Gral_Sexo { get; set; }
        public virtual Tbl_Sol_Solicitud Tbl_Sol_Solicitud { get; set; }
    }
}
