//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_RepresentanteLegal
    {
        public long RepresentanteLegal_id { get; set; }
        public Nullable<int> RepresentanteLegatTipo_id { get; set; }
        public long Solicitud_id { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string No_NIT { get; set; }
        public int RepresententeDocumentoID_Tipo { get; set; }
        public string RepresentanteNo_Documento { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public Nullable<System.DateTime> Fecha_InicioNombramiento { get; set; }
        public Nullable<System.DateTime> Fecha_FinNombramiento { get; set; }
        public bool VigenciaIndefinida { get; set; }
        public Nullable<int> Estado_id { get; set; }
        public Nullable<long> UsuarioExterno_id { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
    
        public virtual Tbl_Gral_DocumentoID_Tipo Tbl_Gral_DocumentoID_Tipo { get; set; }
        public virtual Tbl_Sol_RepresentanteLegal_Estado Tbl_Sol_RepresentanteLegal_Estado { get; set; }
        public virtual Tbl_Sol_RepresentanteLegalTipo Tbl_Sol_RepresentanteLegalTipo { get; set; }
        public virtual Tbl_Sol_Solicitud Tbl_Sol_Solicitud { get; set; }
    }
}
