//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gest_EtapaSolicitud_Inactivacion_Parrafos
    {
        public long Solicitud_id { get; set; }
        public int Doc_TecPro_Tipo_id { get; set; }
        public string Parrafo_1 { get; set; }
        public string Parrafo_2 { get; set; }
        public string Parrafo_3 { get; set; }
        public string Parrafo_4 { get; set; }
        public string Parrafo_5 { get; set; }
        public string Parrafo_6 { get; set; }
        public string Parrafo_7 { get; set; }
        public string Parrafo_8 { get; set; }
        public string Parrafo_9 { get; set; }
        public string Parrafo_10 { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
    
        public virtual Tbl_Gest_EtapaSolicitud_Inactivacion_Tipo Tbl_Gest_EtapaSolicitud_Inactivacion_Tipo { get; set; }
    }
}
