//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Seg_UsuarioExterno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Seg_UsuarioExterno()
        {
            this.Tbl_Seg_UsuarioExterno_Dependiente = new HashSet<Tbl_Seg_UsuarioExterno_Dependiente>();
            this.Tbl_Seg_UsuarioExterno_Dependiente1 = new HashSet<Tbl_Seg_UsuarioExterno_Dependiente>();
            this.Tbl_Sol_Solicitud = new HashSet<Tbl_Sol_Solicitud>();
        }
    
        public long Usuario_id { get; set; }
        public string Correo { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Clave { get; set; }
        public bool CambioPW { get; set; }
        public string Telefono_Celular { get; set; }
        public string Telefono_Oficina { get; set; }
        public string Telefono_Oficina_Extension { get; set; }
        public int PuebloPertenencia_id { get; set; }
        public int Sexo_id { get; set; }
        public int DocumentoID_Tipo { get; set; }
        public string No_Documento { get; set; }
        public string No_NIT { get; set; }
        public int DepartamentoDPI_id { get; set; }
        public int MunicipioDPI_id { get; set; }
        public string Direccion { get; set; }
        public int Municipio_id { get; set; }
        public int Departamento_id { get; set; }
        public string Lugar_Nacimiento { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
        public bool Grado_Academico_Tecnico { get; set; }
        public bool Grado_Academico_Profesional { get; set; }
        public string No_Colegiado { get; set; }
        public string Universidad { get; set; }
        public string UniversidadEspecificarCarrera { get; set; }
        public Nullable<int> Profesion_id { get; set; }
        public bool PostGradoMateriaForestal { get; set; }
        public string PostGradoEspecialidad { get; set; }
        public string PostGradoUniversidad { get; set; }
        public string EspecificarCarrera { get; set; }
        public string No_De_Diploma { get; set; }
        public bool Estado_id { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdateUsuarioInterno { get; set; }
        public Nullable<System.Guid> UsuarioExternoGuid_id { get; set; }
        public Nullable<bool> NotificacionWhatsapp { get; set; }
        public string No_CasilleroElectronico { get; set; }
    
        public virtual Tbl_Gral_Departamento Tbl_Gral_Departamento { get; set; }
        public virtual Tbl_Gral_Departamento Tbl_Gral_Departamento1 { get; set; }
        public virtual Tbl_Gral_DocumentoID_Tipo Tbl_Gral_DocumentoID_Tipo { get; set; }
        public virtual Tbl_Gral_Municipio Tbl_Gral_Municipio { get; set; }
        public virtual Tbl_Gral_Municipio Tbl_Gral_Municipio1 { get; set; }
        public virtual Tbl_Gral_Profesion Tbl_Gral_Profesion { get; set; }
        public virtual Tbl_Gral_PuebloPertenencia Tbl_Gral_PuebloPertenencia { get; set; }
        public virtual Tbl_Gral_Sexo Tbl_Gral_Sexo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Seg_UsuarioExterno_Dependiente> Tbl_Seg_UsuarioExterno_Dependiente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Seg_UsuarioExterno_Dependiente> Tbl_Seg_UsuarioExterno_Dependiente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_Solicitud> Tbl_Sol_Solicitud { get; set; }
    }
}
