//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gral_Tarifario_Sub_Categoria
    {
        public int Categoria_id { get; set; }
        public int Sub_Categoria_id { get; set; }
        public int Correlativo_id { get; set; }
        public string Descripcion { get; set; }
        public string CostoInscripcion { get; set; }
        public string CostoActualizacion { get; set; }
        public Nullable<int> Vigencia { get; set; }
    }
}
