//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gest_EtapaSolicitud_RespuestaDocumentoTipo
    {
        public long Solicitud_id { get; set; }
        public int Etapa_Respuesta_id { get; set; }
        public int Etapa_id { get; set; }
        public decimal EtapaRuta_id { get; set; }
        public int CorrelativoEtapa_id { get; set; }
        public int Tipo_Documento_id { get; set; }
        public int Correlativo_id { get; set; }
        public string ArchivoNombre { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
    
        public virtual Tbl_Gest_EtapaSolicitud Tbl_Gest_EtapaSolicitud { get; set; }
        public virtual Tbl_Sol_DocumentoTipo Tbl_Sol_DocumentoTipo { get; set; }
    }
}
