//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RNF_Rodal_Cultivo
    {
        public string No_Registro { get; set; }
        public string No_RegistroLiteral { get; set; }
        public int No_RegistroCorrelativo { get; set; }
        public long Solicitud_id { get; set; }
        public long Finca_id { get; set; }
        public int Tipo_de_Area { get; set; }
        public long Rodal_Id { get; set; }
        public int Cultivo_id { get; set; }
        public int Anio_Establecimiento { get; set; }
        public Nullable<decimal> Volumen_Rodal { get; set; }
        public Nullable<decimal> Volumen_ha { get; set; }
    
        public virtual Tbl_Gral_Cultivo Tbl_Gral_Cultivo { get; set; }
        public virtual Tbl_RNF_Rodal Tbl_RNF_Rodal { get; set; }
        public virtual Tbl_Sol_Rodal_Tipo Tbl_Sol_Rodal_Tipo { get; set; }
    }
}
