//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RNF_Empresa_EntidadHistory
    {
        public string No_Registro { get; set; }
        public string No_RegistroLiteral { get; set; }
        public int No_RegistroCorrelativo { get; set; }
        public long Solicitud_id { get; set; }
        public string Nombre { get; set; }
        public string No_NIT { get; set; }
        public string DireccionEmpresa { get; set; }
        public Nullable<int> DepartamentoEmpresaEntidad_id { get; set; }
        public Nullable<int> MunicipioEmpresaEntidad_id { get; set; }
        public string DireccionEmpresaMovil { get; set; }
        public Nullable<int> DepartamentoEmpresaMovilEntidad_id { get; set; }
        public Nullable<int> MunicipioEmpresaMovilEntidad_id { get; set; }
        public string Telefono { get; set; }
        public string email { get; set; }
        public Nullable<decimal> GTMX { get; set; }
        public Nullable<decimal> GTMY { get; set; }
        public Nullable<decimal> GTMX_Tecnico { get; set; }
        public Nullable<decimal> GTMY_Tecnico { get; set; }
        public Nullable<long> UsuarioExterno_id { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
        public Nullable<decimal> CapacidadInstalada { get; set; }
        public string Aldea { get; set; }
        public string Objeto_Empresa { get; set; }
        public Nullable<int> Tipo_Industria_id { get; set; }
        public string RNF_Inscripcion_Vinculada { get; set; }
    }
}
