//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gral_CargaDetalle
    {
        public int Tipo_Carga_id { get; set; }
        public long Carga_id { get; set; }
        public int Correlativo_id { get; set; }
        public string Campo01 { get; set; }
        public string Campo02 { get; set; }
        public string Campo03 { get; set; }
        public string Campo04 { get; set; }
        public string Campo05 { get; set; }
        public string Campo06 { get; set; }
        public string Campo07 { get; set; }
        public string Campo08 { get; set; }
        public string Campo09 { get; set; }
        public string Campo10 { get; set; }
        public string Campo11 { get; set; }
        public string Campo12 { get; set; }
        public string Campo13 { get; set; }
        public string Campo14 { get; set; }
        public string Campo15 { get; set; }
        public string Campo16 { get; set; }
        public string Campo17 { get; set; }
        public string Campo18 { get; set; }
        public string Campo19 { get; set; }
        public string Campo20 { get; set; }
    
        public virtual Tbl_Gral_Carga Tbl_Gral_Carga { get; set; }
    }
}
