//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_Solicitud_Sub_Sub_Categoria
    {
        public int Categoria_id { get; set; }
        public int Sub_Categoria_id { get; set; }
        public int Sub_Sub_Categoria_id { get; set; }
        public string Descripcion { get; set; }
        public string CodigoRNF { get; set; }
        public string CodigoDeServicioINAB { get; set; }
        public string Modalidad { get; set; }
        public Nullable<bool> Procedencia_Probosque { get; set; }
        public Nullable<bool> Procedencia_PinpepOld { get; set; }
        public Nullable<bool> Procedencia_PinpepNew { get; set; }
        public Nullable<bool> Procedencia_Secorf { get; set; }
    }
}
