//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_API_Gral_Especie
    {
        public string Especie_Id { get; set; }
        public string NombreCientifico { get; set; }
        public string NombresComunes { get; set; }
        public string Autores { get; set; }
        public string Sinonimos { get; set; }
        public string Familia { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<bool> ArbolFrutal { get; set; }
        public Nullable<bool> Conifera { get; set; }
        public Nullable<bool> Latifoliada { get; set; }
        public Nullable<bool> Estado_id { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<System.DateTime> swdateupdated { get; set; }
        public Nullable<long> swupdatedby { get; set; }
        public Nullable<bool> swupdatedbyinterno { get; set; }
    }
}
