//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sol_DocumentoTipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Sol_DocumentoTipo()
        {
            this.Tbl_Gest_Etapa_RespuestaDocumentoTipo = new HashSet<Tbl_Gest_Etapa_RespuestaDocumentoTipo>();
            this.Tbl_Gest_EtapaSolicitud_RespuestaDocumentoTipo = new HashSet<Tbl_Gest_EtapaSolicitud_RespuestaDocumentoTipo>();
            this.Tbl_Sol_DocumentosSolicitar = new HashSet<Tbl_Sol_DocumentosSolicitar>();
            this.Tbl_Sol_DocumentoSubido = new HashSet<Tbl_Sol_DocumentoSubido>();
        }
    
        public int Tipo_Documento_id { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> Finca { get; set; }
        public Nullable<bool> Rodal { get; set; }
        public Nullable<bool> PropietarioIndividual { get; set; }
        public Nullable<bool> PropietarioJuridico { get; set; }
        public Nullable<bool> Representante_Legal { get; set; }
        public Nullable<bool> Etapa { get; set; }
        public string EjemploHref { get; set; }
        public Nullable<bool> Obligatorio { get; set; }
        public string ReglaHeuristica { get; set; }
        public Nullable<bool> ValidacionJuridica { get; set; }
        public string DescripcionCategoria_01 { get; set; }
        public string DescripcionCategoria_02 { get; set; }
        public string DescripcionCategoria_03 { get; set; }
        public string DescripcionCategoria_04 { get; set; }
        public string DescripcionCategoria_05 { get; set; }
        public string DescripcionCategoria_06 { get; set; }
        public string DescripcionCategoria_07 { get; set; }
        public string DescripcionCategoria_08 { get; set; }
        public string DescripcionCategoria_09 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Gest_Etapa_RespuestaDocumentoTipo> Tbl_Gest_Etapa_RespuestaDocumentoTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Gest_EtapaSolicitud_RespuestaDocumentoTipo> Tbl_Gest_EtapaSolicitud_RespuestaDocumentoTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_DocumentosSolicitar> Tbl_Sol_DocumentosSolicitar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sol_DocumentoSubido> Tbl_Sol_DocumentoSubido { get; set; }
    }
}
