//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gral_Carga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Gral_Carga()
        {
            this.Tbl_Gral_CargaDetalle = new HashSet<Tbl_Gral_CargaDetalle>();
        }
    
        public int Tipo_Carga_id { get; set; }
        public long Carga_id { get; set; }
        public Nullable<long> Solicitud_id { get; set; }
        public Nullable<long> Finca_id { get; set; }
        public Nullable<long> Rodal_id { get; set; }
        public Nullable<int> Estatus_id { get; set; }
        public Nullable<int> AreaProtegida_id { get; set; }
        public string Departamento { get; set; }
        public string Municipio { get; set; }
        public string Region { get; set; }
        public string Sub_Region { get; set; }
        public Nullable<System.DateTime> swdatecreated { get; set; }
        public Nullable<long> swcreatedby { get; set; }
        public Nullable<bool> swcreatedbyinterno { get; set; }
        public string CODIGO { get; set; }
        public string CodReg { get; set; }
        public string CodSubreg { get; set; }
        public string Depto { get; set; }
        public string No_Registro { get; set; }
        public string No_RegistroLiteral { get; set; }
        public Nullable<int> No_RegistroCorrelativo { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Tbl_Gral_Carga_Estatus Tbl_Gral_Carga_Estatus { get; set; }
        public virtual Tbl_Gral_CargaTipo Tbl_Gral_CargaTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Gral_CargaDetalle> Tbl_Gral_CargaDetalle { get; set; }
    }
}
