//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CategoriaSubySubSub
    {
        public int Categoria_id { get; set; }
        public string CDescripcion { get; set; }
        public string CatCodigoRNF { get; set; }
        public Nullable<int> Sub_Categoria_id { get; set; }
        public string SubDescripcion { get; set; }
        public string CodigoRNF { get; set; }
        public string CodigoServicioINAB { get; set; }
        public Nullable<int> Sub_Sub_Categoria_id { get; set; }
        public string SubSubDescripcion { get; set; }
    }
}
