//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_UsuariosPermisos
    {
        public string Nombre_Completo { get; set; }
        public string Email { get; set; }
        public string Estado { get; set; }
        public string Permisos_Asignados { get; set; }
        public string Whatsapp { get; set; }
        public string Nombre_Region { get; set; }
        public string Nombre_SubRegion { get; set; }
        public string No_SubRegion { get; set; }
    }
}
